-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity card_recognizer_hw_find_largest_component_hw is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0);
    binary_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
    binary_ce0 : OUT STD_LOGIC;
    binary_q0 : IN STD_LOGIC_VECTOR (1 downto 0);
    binary_address1 : OUT STD_LOGIC_VECTOR (18 downto 0);
    binary_ce1 : OUT STD_LOGIC;
    binary_q1 : IN STD_LOGIC_VECTOR (1 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_156_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_156_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_156_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_156_p_ce : OUT STD_LOGIC );
end;


architecture behav of card_recognizer_hw_find_largest_component_hw is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (20 downto 0) := "000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (20 downto 0) := "000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (20 downto 0) := "000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (20 downto 0) := "000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (20 downto 0) := "000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (20 downto 0) := "000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (20 downto 0) := "000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (20 downto 0) := "000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (20 downto 0) := "000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (20 downto 0) := "001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (20 downto 0) := "010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (20 downto 0) := "100000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal visited_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal visited_ce0 : STD_LOGIC;
    signal visited_we0 : STD_LOGIC;
    signal visited_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal visited_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal visited_ce1 : STD_LOGIC;
    signal visited_we1 : STD_LOGIC;
    signal visited_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal queue_x_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal queue_x_ce0 : STD_LOGIC;
    signal queue_x_we0 : STD_LOGIC;
    signal queue_x_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal queue_x_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal queue_y_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal queue_y_ce0 : STD_LOGIC;
    signal queue_y_we0 : STD_LOGIC;
    signal queue_y_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal queue_y_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_137_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_143 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal trunc_ln38_fu_155_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln38_reg_366 : STD_LOGIC_VECTOR (18 downto 0);
    signal n_reg_371 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_185_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln38_reg_386 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln39_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_394 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln38_fu_211_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln38_reg_402 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln38_1_fu_226_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln38_1_reg_407 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln38_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln38_2_fu_238_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal select_ln38_fu_242_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln38_reg_423 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln40_fu_252_p2 : STD_LOGIC_VECTOR (18 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln40_fu_252_p2 : signal is "no";
    signal add_ln40_reg_429 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln42_fu_257_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_reg_434 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal icmp_ln42_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_444 : STD_LOGIC_VECTOR (0 downto 0);
    signal visited_addr_1_reg_448 : STD_LOGIC_VECTOR (18 downto 0);
    signal visited_load_reg_453 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal zext_ln48_fu_267_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_start : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_done : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_idle : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_ready : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_ce0 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_we0 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_start : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_done : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_idle : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_ready : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_best_count_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_best_count_3_out_ap_vld : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_ce0 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_we0 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_ce0 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_we0 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_ce0 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_address1 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_ce1 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_ce0 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_we0 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_address1 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_ce1 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_we1 : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_d1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_ce : STD_LOGIC;
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_start_reg : STD_LOGIC := '0';
    signal grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_NS_fsm_state19 : STD_LOGIC;
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal best_count_3_loc_fu_60 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_fu_44 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln39_fu_293_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal y_fu_48 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_52 : STD_LOGIC_VECTOR (63 downto 0);
    signal best_count_fu_56 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln70_fu_280_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_137_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_149_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_149_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln38_fu_155_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln38_fu_179_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln38_1_fu_182_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_185_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_185_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln39_fu_197_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln39_fu_201_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln38_1_fu_220_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln39_fu_248_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_311_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln70_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_311_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_149_ce : STD_LOGIC;
    signal grp_fu_185_ce : STD_LOGIC;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal grp_fu_185_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_185_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component card_recognizer_hw_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        n : IN STD_LOGIC_VECTOR (31 downto 0);
        visited_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        visited_ce0 : OUT STD_LOGIC;
        visited_we0 : OUT STD_LOGIC;
        visited_d0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component card_recognizer_hw_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        height : IN STD_LOGIC_VECTOR (31 downto 0);
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        best_count_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        best_count_3_out_ap_vld : OUT STD_LOGIC;
        queue_x_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        queue_x_ce0 : OUT STD_LOGIC;
        queue_x_we0 : OUT STD_LOGIC;
        queue_x_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        queue_x_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        queue_y_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        queue_y_ce0 : OUT STD_LOGIC;
        queue_y_we0 : OUT STD_LOGIC;
        queue_y_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        queue_y_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        binary_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        binary_ce0 : OUT STD_LOGIC;
        binary_q0 : IN STD_LOGIC_VECTOR (1 downto 0);
        binary_address1 : OUT STD_LOGIC_VECTOR (18 downto 0);
        binary_ce1 : OUT STD_LOGIC;
        binary_q1 : IN STD_LOGIC_VECTOR (1 downto 0);
        visited_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        visited_ce0 : OUT STD_LOGIC;
        visited_we0 : OUT STD_LOGIC;
        visited_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        visited_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        visited_address1 : OUT STD_LOGIC_VECTOR (18 downto 0);
        visited_ce1 : OUT STD_LOGIC;
        visited_we1 : OUT STD_LOGIC;
        visited_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        visited_q1 : IN STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_149_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_149_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_149_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_149_p_ce : OUT STD_LOGIC );
    end component;


    component card_recognizer_hw_sitofp_32ns_32_6_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component card_recognizer_hw_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component card_recognizer_hw_mul_32ns_32ns_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component card_recognizer_hw_mul_mul_19s_19s_19_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (18 downto 0);
        din1 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component card_recognizer_hw_find_largest_component_hw_visited_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        address1 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (0 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component card_recognizer_hw_find_largest_component_hw_queue_x_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    visited_U : component card_recognizer_hw_find_largest_component_hw_visited_RAM_AUTO_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 307200,
        AddressWidth => 19)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => visited_address0,
        ce0 => visited_ce0,
        we0 => visited_we0,
        d0 => visited_d0,
        q0 => visited_q0,
        address1 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_address1,
        ce1 => visited_ce1,
        we1 => visited_we1,
        d1 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_d1,
        q1 => visited_q1);

    queue_x_U : component card_recognizer_hw_find_largest_component_hw_queue_x_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 307200,
        AddressWidth => 19)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => queue_x_address0,
        ce0 => queue_x_ce0,
        we0 => queue_x_we0,
        d0 => queue_x_d0,
        q0 => queue_x_q0);

    queue_y_U : component card_recognizer_hw_find_largest_component_hw_queue_x_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 307200,
        AddressWidth => 19)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => queue_y_address0,
        ce0 => queue_y_ce0,
        we0 => queue_y_we0,
        d0 => queue_y_d0,
        q0 => queue_y_q0);

    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115 : component card_recognizer_hw_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_start,
        ap_done => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_done,
        ap_idle => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_idle,
        ap_ready => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_ready,
        n => n_reg_371,
        visited_address0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_address0,
        visited_ce0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_ce0,
        visited_we0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_we0,
        visited_d0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_d0);

    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122 : component card_recognizer_hw_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_start,
        ap_done => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_done,
        ap_idle => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_idle,
        ap_ready => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_ready,
        height => height,
        width => width,
        best_count_3_out => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_best_count_3_out,
        best_count_3_out_ap_vld => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_best_count_3_out_ap_vld,
        queue_x_address0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_address0,
        queue_x_ce0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_ce0,
        queue_x_we0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_we0,
        queue_x_d0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_d0,
        queue_x_q0 => queue_x_q0,
        queue_y_address0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_address0,
        queue_y_ce0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_ce0,
        queue_y_we0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_we0,
        queue_y_d0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_d0,
        queue_y_q0 => queue_y_q0,
        binary_address0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_address0,
        binary_ce0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_ce0,
        binary_q0 => binary_q0,
        binary_address1 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_address1,
        binary_ce1 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_ce1,
        binary_q1 => binary_q1,
        visited_address0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_address0,
        visited_ce0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_ce0,
        visited_we0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_we0,
        visited_d0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_d0,
        visited_q0 => visited_q0,
        visited_address1 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_address1,
        visited_ce1 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_ce1,
        visited_we1 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_we1,
        visited_d1 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_d1,
        visited_q1 => visited_q1,
        grp_fu_149_p_din0 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_din0,
        grp_fu_149_p_din1 => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_din1,
        grp_fu_149_p_dout0 => grp_fu_156_p_dout0,
        grp_fu_149_p_ce => grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_ce);

    sitofp_32ns_32_6_no_dsp_1_U32 : component card_recognizer_hw_sitofp_32ns_32_6_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_137_p0,
        ce => ap_const_logic_1,
        dout => grp_fu_137_p1);

    mul_32ns_32ns_64_2_1_U34 : component card_recognizer_hw_mul_32ns_32ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_185_p0,
        din1 => grp_fu_185_p1,
        ce => grp_fu_185_ce,
        dout => grp_fu_185_p2);

    mul_mul_19s_19s_19_4_1_U35 : component card_recognizer_hw_mul_mul_19s_19s_19_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 19,
        din1_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_311_p0,
        din1 => trunc_ln38_reg_366,
        ce => ap_const_logic_1,
        dout => grp_fu_311_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_ready = ap_const_logic_1)) then 
                    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state19) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_ready = ap_const_logic_1)) then 
                    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    best_count_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                best_count_fu_56 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state21) and (visited_load_reg_453 = ap_const_lv1_0) and (icmp_ln42_reg_444 = ap_const_lv1_1))) then 
                best_count_fu_56 <= select_ln70_fu_280_p3;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_fu_52 <= ap_const_lv64_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                indvar_flatten_fu_52 <= add_ln38_reg_402;
            end if; 
        end if;
    end process;

    x_fu_44_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                x_fu_44 <= ap_const_lv31_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                x_fu_44 <= add_ln39_fu_293_p2;
            end if; 
        end if;
    end process;

    y_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_48 <= ap_const_lv31_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                y_fu_48 <= select_ln38_1_reg_407;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln38_reg_402 <= add_ln38_fu_211_p2;
                icmp_ln39_reg_394 <= icmp_ln39_fu_201_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln40_reg_429 <= add_ln40_fu_252_p2;
                select_ln38_reg_423 <= select_ln38_fu_242_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_best_count_3_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                best_count_3_loc_fu_60 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_best_count_3_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                icmp_ln42_reg_444 <= icmp_ln42_fu_261_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                mul_ln38_reg_386 <= grp_fu_185_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                n_reg_371 <= grp_fu_156_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state11))) then
                reg_143 <= grp_fu_137_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln38_fu_206_p2 = ap_const_lv1_0))) then
                select_ln38_1_reg_407 <= select_ln38_1_fu_226_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                trunc_ln38_reg_366 <= trunc_ln38_fu_155_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (icmp_ln42_fu_261_p2 = ap_const_lv1_1))) then
                visited_addr_1_reg_448 <= zext_ln42_reg_434(19 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln42_reg_444 = ap_const_lv1_1))) then
                visited_load_reg_453 <= visited_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                    zext_ln42_reg_434(18 downto 0) <= zext_ln42_fu_257_p1(18 downto 0);
            end if;
        end if;
    end process;
    zext_ln42_reg_434(63 downto 19) <= "000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, visited_q0, ap_CS_fsm_state4, ap_CS_fsm_state5, icmp_ln38_fu_206_p2, icmp_ln42_reg_444, ap_CS_fsm_state12, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_done, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_done, ap_CS_fsm_state20)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln38_fu_206_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and ((visited_q0 = ap_const_lv1_1) or (icmp_ln42_reg_444 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                if (((grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln38_1_fu_220_p2 <= std_logic_vector(unsigned(y_fu_48) + unsigned(ap_const_lv31_1));
    add_ln38_fu_211_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_52) + unsigned(ap_const_lv64_1));
    add_ln39_fu_293_p2 <= std_logic_vector(unsigned(select_ln38_reg_423) + unsigned(ap_const_lv31_1));
    add_ln40_fu_252_p2 <= std_logic_vector(unsigned(trunc_ln39_fu_248_p1) + unsigned(grp_fu_311_p2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_NS_fsm_state19 <= ap_NS_fsm(18);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state20_blk_assign_proc : process(grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_done)
    begin
        if ((grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state20_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state20_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_done)
    begin
        if ((grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5, icmp_ln38_fu_206_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln38_fu_206_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln38_fu_206_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln38_fu_206_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= best_count_fu_56;

    binary_address0_assign_proc : process(zext_ln42_fu_257_p1, ap_CS_fsm_state10, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_address0, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            binary_address0 <= zext_ln42_fu_257_p1(19 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            binary_address0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_address0;
        else 
            binary_address0 <= "XXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    binary_address1 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_address1;

    binary_ce0_assign_proc : process(ap_CS_fsm_state10, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_ce0, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            binary_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            binary_ce0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_ce0;
        else 
            binary_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    binary_ce1_assign_proc : process(grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_ce1, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            binary_ce1 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_binary_ce1;
        else 
            binary_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_start <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_start_reg;
    grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_start <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_ap_start_reg;

    grp_fu_137_p0_assign_proc : process(zext_ln38_2_fu_238_p1, ap_CS_fsm_state6, ap_CS_fsm_state12, zext_ln48_fu_267_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_137_p0 <= zext_ln48_fu_267_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_137_p0 <= zext_ln38_2_fu_238_p1;
        else 
            grp_fu_137_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_149_ce_assign_proc : process(grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_ce, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_149_ce <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_ce;
        else 
            grp_fu_149_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_149_p0_assign_proc : process(ap_CS_fsm_state1, height, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_din0, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_149_p0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_149_p0 <= height;
        else 
            grp_fu_149_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_149_p1_assign_proc : process(ap_CS_fsm_state1, width, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_din1, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_149_p1 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_grp_fu_149_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_149_p1 <= width;
        else 
            grp_fu_149_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_156_p_ce <= grp_fu_149_ce;
    grp_fu_156_p_din0 <= grp_fu_149_p0;
    grp_fu_156_p_din1 <= grp_fu_149_p1;

    grp_fu_185_ce_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_ap_done = ap_const_logic_1)))) then 
            grp_fu_185_ce <= ap_const_logic_1;
        else 
            grp_fu_185_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_185_p0 <= grp_fu_185_p00(32 - 1 downto 0);
    grp_fu_185_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln38_fu_179_p0),64));
    grp_fu_185_p1 <= grp_fu_185_p10(32 - 1 downto 0);
    grp_fu_185_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln38_1_fu_182_p0),64));
    grp_fu_311_p0 <= select_ln38_1_fu_226_p3(19 - 1 downto 0);
    icmp_ln38_fu_206_p2 <= "1" when (indvar_flatten_fu_52 = mul_ln38_reg_386) else "0";
    icmp_ln39_fu_201_p1 <= width;
    icmp_ln39_fu_201_p2 <= "1" when (signed(zext_ln39_fu_197_p1) < signed(icmp_ln39_fu_201_p1)) else "0";
    icmp_ln42_fu_261_p2 <= "1" when (binary_q0 = ap_const_lv2_3) else "0";
    icmp_ln70_fu_274_p2 <= "1" when (signed(best_count_3_loc_fu_60) > signed(best_count_fu_56)) else "0";

    queue_x_address0_assign_proc : process(grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_address0, ap_CS_fsm_state18, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            queue_x_address0 <= ap_const_lv19_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            queue_x_address0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_address0;
        else 
            queue_x_address0 <= "XXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    queue_x_ce0_assign_proc : process(grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_ce0, ap_CS_fsm_state18, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            queue_x_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            queue_x_ce0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_ce0;
        else 
            queue_x_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    queue_x_d0_assign_proc : process(reg_143, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_d0, ap_CS_fsm_state18, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            queue_x_d0 <= reg_143;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            queue_x_d0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_d0;
        else 
            queue_x_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    queue_x_we0_assign_proc : process(grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_we0, ap_CS_fsm_state18, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            queue_x_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            queue_x_we0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_x_we0;
        else 
            queue_x_we0 <= ap_const_logic_0;
        end if; 
    end process;


    queue_y_address0_assign_proc : process(ap_CS_fsm_state12, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_address0, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            queue_y_address0 <= ap_const_lv19_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            queue_y_address0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_address0;
        else 
            queue_y_address0 <= "XXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    queue_y_ce0_assign_proc : process(ap_CS_fsm_state12, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_ce0, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            queue_y_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            queue_y_ce0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_ce0;
        else 
            queue_y_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    queue_y_d0_assign_proc : process(reg_143, ap_CS_fsm_state12, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_d0, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            queue_y_d0 <= reg_143;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            queue_y_d0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_d0;
        else 
            queue_y_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    queue_y_we0_assign_proc : process(visited_q0, icmp_ln42_reg_444, ap_CS_fsm_state12, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_we0, ap_CS_fsm_state20)
    begin
        if (((visited_q0 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln42_reg_444 = ap_const_lv1_1))) then 
            queue_y_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            queue_y_we0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_queue_y_we0;
        else 
            queue_y_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln38_1_fu_226_p3 <= 
        y_fu_48 when (icmp_ln39_fu_201_p2(0) = '1') else 
        add_ln38_1_fu_220_p2;
    select_ln38_fu_242_p3 <= 
        x_fu_44 when (icmp_ln39_reg_394(0) = '1') else 
        ap_const_lv31_0;
    select_ln70_fu_280_p3 <= 
        best_count_3_loc_fu_60 when (icmp_ln70_fu_274_p2(0) = '1') else 
        best_count_fu_56;
    trunc_ln38_fu_155_p0 <= width;
    trunc_ln38_fu_155_p1 <= trunc_ln38_fu_155_p0(19 - 1 downto 0);
    trunc_ln39_fu_248_p1 <= select_ln38_fu_242_p3(19 - 1 downto 0);

    visited_address0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state4, zext_ln42_reg_434, visited_addr_1_reg_448, ap_CS_fsm_state12, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_address0, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_address0, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            visited_address0 <= visited_addr_1_reg_448;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            visited_address0 <= zext_ln42_reg_434(19 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            visited_address0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            visited_address0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_address0;
        else 
            visited_address0 <= "XXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    visited_ce0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state4, ap_CS_fsm_state12, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_ce0, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_ce0, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            visited_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            visited_ce0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            visited_ce0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_ce0;
        else 
            visited_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    visited_ce1_assign_proc : process(grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_ce1, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            visited_ce1 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_ce1;
        else 
            visited_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    visited_d0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state12, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_d0, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_d0, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            visited_d0 <= ap_const_lv1_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            visited_d0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            visited_d0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_d0;
        else 
            visited_d0 <= "X";
        end if; 
    end process;


    visited_we0_assign_proc : process(visited_q0, ap_CS_fsm_state4, icmp_ln42_reg_444, ap_CS_fsm_state12, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_we0, grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_we0, ap_CS_fsm_state20)
    begin
        if (((visited_q0 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln42_reg_444 = ap_const_lv1_1))) then 
            visited_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            visited_we0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            visited_we0 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_31_1_fu_115_visited_we0;
        else 
            visited_we0 <= ap_const_logic_0;
        end if; 
    end process;


    visited_we1_assign_proc : process(grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_we1, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            visited_we1 <= grp_find_largest_component_hw_Pipeline_VITIS_LOOP_51_4_fu_122_visited_we1;
        else 
            visited_we1 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln38_1_fu_182_p0 <= width;
    zext_ln38_2_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln38_1_reg_407),32));
    zext_ln38_fu_179_p0 <= height;
    zext_ln39_fu_197_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_fu_44),32));
    zext_ln42_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln40_reg_429),64));
    zext_ln48_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln38_reg_423),32));
end behav;
