// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="card_recognizer_hw_card_recognizer_hw,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=31.818562,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2400,HLS_SYN_DSP=0,HLS_SYN_FF=4069,HLS_SYN_LUT=9303,HLS_VERSION=2022_2}" *)

module card_recognizer_hw (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_rgb;
wire   [31:0] result_rank;
reg    result_rank_ap_vld;
reg    result_suit_ap_vld;
wire   [31:0] width;
wire   [31:0] height;
reg   [18:0] gray_address0;
reg    gray_ce0;
reg    gray_we0;
wire   [7:0] gray_q0;
reg   [18:0] binary_address0;
reg    binary_ce0;
reg    binary_we0;
wire   [1:0] binary_q0;
reg    binary_ce1;
wire   [1:0] binary_q1;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state5;
reg   [31:0] height_read_reg_199;
reg   [31:0] width_read_reg_205;
reg   [63:0] input_rgb_read_reg_211;
wire   [31:0] grp_fu_156_p2;
reg   [31:0] n_reg_217;
wire    ap_CS_fsm_state3;
wire   [30:0] trunc_ln105_fu_165_p1;
reg   [30:0] trunc_ln105_reg_228;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln105_fu_160_p2;
wire   [31:0] sub_ln105_fu_173_p2;
reg   [31:0] sub_ln105_reg_234;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_start;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_done;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_idle;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_ready;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWVALID;
wire   [63:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWADDR;
wire   [0:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWID;
wire   [31:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWLEN;
wire   [2:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWSIZE;
wire   [1:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWBURST;
wire   [1:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWLOCK;
wire   [3:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWCACHE;
wire   [2:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWPROT;
wire   [3:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWQOS;
wire   [3:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWREGION;
wire   [0:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWUSER;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WVALID;
wire   [7:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WDATA;
wire   [0:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WSTRB;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WLAST;
wire   [0:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WID;
wire   [0:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WUSER;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARVALID;
wire   [63:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARADDR;
wire   [0:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARID;
wire   [31:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARLEN;
wire   [2:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARSIZE;
wire   [1:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARBURST;
wire   [1:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARLOCK;
wire   [3:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARCACHE;
wire   [2:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARPROT;
wire   [3:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARQOS;
wire   [3:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARREGION;
wire   [0:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARUSER;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_RREADY;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_BREADY;
wire   [18:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_address0;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_ce0;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_we0;
wire   [7:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_d0;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_start;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_done;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_idle;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_ready;
wire   [18:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_gray_address0;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_gray_ce0;
wire   [18:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_address0;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_ce0;
wire    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_we0;
wire   [1:0] grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_d0;
wire    grp_find_largest_component_hw_fu_142_ap_start;
wire    grp_find_largest_component_hw_fu_142_ap_done;
wire    grp_find_largest_component_hw_fu_142_ap_idle;
wire    grp_find_largest_component_hw_fu_142_ap_ready;
wire   [18:0] grp_find_largest_component_hw_fu_142_binary_address0;
wire    grp_find_largest_component_hw_fu_142_binary_ce0;
wire   [18:0] grp_find_largest_component_hw_fu_142_binary_address1;
wire    grp_find_largest_component_hw_fu_142_binary_ce1;
wire   [31:0] grp_find_largest_component_hw_fu_142_ap_return;
wire  signed [31:0] grp_find_largest_component_hw_fu_142_grp_fu_156_p_din0;
wire  signed [31:0] grp_find_largest_component_hw_fu_142_grp_fu_156_p_din1;
wire    grp_find_largest_component_hw_fu_142_grp_fu_156_p_ce;
wire    gmem_AWREADY;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [7:0] gmem_RDATA;
wire   [10:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg    grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_find_largest_component_hw_fu_142_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg  signed [31:0] grp_fu_156_p0;
reg  signed [31:0] grp_fu_156_p1;
wire    ap_CS_fsm_state2;
wire   [31:0] shl_ln105_fu_168_p2;
wire   [0:0] icmp_ln123_fu_184_p2;
reg    grp_fu_156_ce;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_start_reg = 1'b0;
#0 grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_start_reg = 1'b0;
#0 grp_find_largest_component_hw_fu_142_ap_start_reg = 1'b0;
end

card_recognizer_hw_gray_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 307200 ),
    .AddressWidth( 19 ))
gray_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(gray_address0),
    .ce0(gray_ce0),
    .we0(gray_we0),
    .d0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_d0),
    .q0(gray_q0)
);

card_recognizer_hw_binary_RAM_AUTO_1R1W #(
    .DataWidth( 2 ),
    .AddressRange( 307200 ),
    .AddressWidth( 19 ))
binary_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(binary_address0),
    .ce0(binary_ce0),
    .we0(binary_we0),
    .d0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_d0),
    .q0(binary_q0),
    .address1(grp_find_largest_component_hw_fu_142_binary_address1),
    .ce1(binary_ce1),
    .q1(binary_q1)
);

card_recognizer_hw_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1 grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_start),
    .ap_done(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_done),
    .ap_idle(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_idle),
    .ap_ready(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_ready),
    .m_axi_gmem_AWVALID(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .input_rgb(input_rgb_read_reg_211),
    .trunc_ln(trunc_ln105_reg_228),
    .gray_address0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_address0),
    .gray_ce0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_ce0),
    .gray_we0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_we0),
    .gray_d0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_d0)
);

card_recognizer_hw_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2 grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_start),
    .ap_done(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_done),
    .ap_idle(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_idle),
    .ap_ready(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_ready),
    .trunc_ln(trunc_ln105_reg_228),
    .gray_address0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_gray_address0),
    .gray_ce0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_gray_ce0),
    .gray_q0(gray_q0),
    .binary_address0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_address0),
    .binary_ce0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_ce0),
    .binary_we0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_we0),
    .binary_d0(grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_d0)
);

card_recognizer_hw_find_largest_component_hw grp_find_largest_component_hw_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_find_largest_component_hw_fu_142_ap_start),
    .ap_done(grp_find_largest_component_hw_fu_142_ap_done),
    .ap_idle(grp_find_largest_component_hw_fu_142_ap_idle),
    .ap_ready(grp_find_largest_component_hw_fu_142_ap_ready),
    .width(width_read_reg_205),
    .height(height_read_reg_199),
    .binary_address0(grp_find_largest_component_hw_fu_142_binary_address0),
    .binary_ce0(grp_find_largest_component_hw_fu_142_binary_ce0),
    .binary_q0(binary_q0),
    .binary_address1(grp_find_largest_component_hw_fu_142_binary_address1),
    .binary_ce1(grp_find_largest_component_hw_fu_142_binary_ce1),
    .binary_q1(binary_q1),
    .ap_return(grp_find_largest_component_hw_fu_142_ap_return),
    .grp_fu_156_p_din0(grp_find_largest_component_hw_fu_142_grp_fu_156_p_din0),
    .grp_fu_156_p_din1(grp_find_largest_component_hw_fu_142_grp_fu_156_p_din1),
    .grp_fu_156_p_dout0(grp_fu_156_p2),
    .grp_fu_156_p_ce(grp_find_largest_component_hw_fu_142_grp_fu_156_p_ce)
);

card_recognizer_hw_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_rgb(input_rgb),
    .result_rank(result_rank),
    .result_rank_ap_vld(result_rank_ap_vld),
    .result_suit(32'd0),
    .result_suit_ap_vld(result_suit_ap_vld),
    .width(width),
    .height(height),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

card_recognizer_hw_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 11 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(1'b0)
);

card_recognizer_hw_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U43(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_156_p0),
    .din1(grp_fu_156_p1),
    .ce(grp_fu_156_ce),
    .dout(grp_fu_156_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_start_reg <= 1'b1;
        end else if ((grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_ready == 1'b1)) begin
            grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_start_reg <= 1'b1;
        end else if ((grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_ready == 1'b1)) begin
            grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_find_largest_component_hw_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_find_largest_component_hw_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_find_largest_component_hw_fu_142_ap_ready == 1'b1)) begin
            grp_find_largest_component_hw_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        height_read_reg_199 <= height;
        input_rgb_read_reg_211 <= input_rgb;
        width_read_reg_205 <= width;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        n_reg_217 <= grp_fu_156_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln105_fu_160_p2 == 1'd1))) begin
        sub_ln105_reg_234 <= sub_ln105_fu_173_p2;
        trunc_ln105_reg_228 <= trunc_ln105_fu_165_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_find_largest_component_hw_fu_142_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_find_largest_component_hw_fu_142_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_find_largest_component_hw_fu_142_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        binary_address0 = grp_find_largest_component_hw_fu_142_binary_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        binary_address0 = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_address0;
    end else begin
        binary_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        binary_ce0 = grp_find_largest_component_hw_fu_142_binary_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        binary_ce0 = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_ce0;
    end else begin
        binary_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        binary_ce1 = grp_find_largest_component_hw_fu_142_binary_ce1;
    end else begin
        binary_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        binary_we0 = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_binary_we0;
    end else begin
        binary_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        gmem_ARADDR = input_rgb_read_reg_211;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARADDR = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        gmem_ARLEN = sub_ln105_reg_234;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARLEN = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARVALID = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_RREADY = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gray_address0 = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_gray_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        gray_address0 = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_address0;
    end else begin
        gray_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gray_ce0 = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_gray_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        gray_ce0 = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_ce0;
    end else begin
        gray_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        gray_we0 = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_gray_we0;
    end else begin
        gray_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_156_ce = grp_find_largest_component_hw_fu_142_grp_fu_156_p_ce;
    end else begin
        grp_fu_156_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_156_p0 = grp_find_largest_component_hw_fu_142_grp_fu_156_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_156_p0 = height_read_reg_199;
    end else begin
        grp_fu_156_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_156_p1 = grp_find_largest_component_hw_fu_142_grp_fu_156_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_156_p1 = width_read_reg_205;
    end else begin
        grp_fu_156_p1 = 'bx;
    end
end

always @ (*) begin
    if (((grp_find_largest_component_hw_fu_142_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        result_rank_ap_vld = 1'b1;
    end else begin
        result_rank_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_find_largest_component_hw_fu_142_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        result_suit_ap_vld = 1'b1;
    end else begin
        result_suit_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln105_fu_160_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_find_largest_component_hw_fu_142_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_start = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_105_1_fu_123_ap_start_reg;

assign grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_start = grp_card_recognizer_hw_Pipeline_VITIS_LOOP_114_2_fu_133_ap_start_reg;

assign grp_find_largest_component_hw_fu_142_ap_start = grp_find_largest_component_hw_fu_142_ap_start_reg;

assign icmp_ln105_fu_160_p2 = (($signed(n_reg_217) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_184_p2 = (($signed(grp_find_largest_component_hw_fu_142_ap_return) > $signed(32'd10000)) ? 1'b1 : 1'b0);

assign result_rank = ((icmp_ln123_fu_184_p2[0:0] == 1'b1) ? 32'd10 : 32'd0);

assign shl_ln105_fu_168_p2 = n_reg_217 << 32'd2;

assign sub_ln105_fu_173_p2 = (shl_ln105_fu_168_p2 - n_reg_217);

assign trunc_ln105_fu_165_p1 = n_reg_217[30:0];

endmodule //card_recognizer_hw
