-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity card_recognizer_hw is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_rgb_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    input_rgb_ce0 : OUT STD_LOGIC;
    input_rgb_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of card_recognizer_hw is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "card_recognizer_hw_card_recognizer_hw,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010i-clg225-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.164000,HLS_SYN_LAT=300658,HLS_SYN_TPT=none,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=1895,HLS_SYN_LUT=3886,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv22_556 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000010101010110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal result_rank_ap_vld : STD_LOGIC;
    signal result_suit_ap_vld : STD_LOGIC;
    signal width : STD_LOGIC_VECTOR (31 downto 0);
    signal height : STD_LOGIC_VECTOR (31 downto 0);
    signal gray_V_ce0 : STD_LOGIC;
    signal gray_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_ce1 : STD_LOGIC;
    signal gray_V_we1 : STD_LOGIC;
    signal binary_V_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal binary_V_ce0 : STD_LOGIC;
    signal binary_V_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal binary_V_ce1 : STD_LOGIC;
    signal binary_V_we1 : STD_LOGIC;
    signal height_read_reg_472 : STD_LOGIC_VECTOR (31 downto 0);
    signal width_read_reg_478 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_188_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal n_reg_491 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln33_fu_197_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln33_reg_500 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln33_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal card_box_min_x_V_reg_506 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal card_box_min_y_V_reg_513 : STD_LOGIC_VECTOR (7 downto 0);
    signal card_box_max_x_V_reg_518 : STD_LOGIC_VECTOR (7 downto 0);
    signal card_box_count_reg_524 : STD_LOGIC_VECTOR (31 downto 0);
    signal card_box_valid_V_fu_221_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal card_box_valid_V_reg_529 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln231_fu_225_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln231_reg_533 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln246_fu_261_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln246_reg_549 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_reg_554 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal trunc_ln233_1_reg_559 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln233_2_reg_564 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_cast_fu_348_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_cast_reg_569 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln234_1_fu_364_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln234_1_reg_574 : STD_LOGIC_VECTOR (7 downto 0);
    signal x1_fu_449_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal x1_reg_579 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal y1_fu_455_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal y1_reg_584 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_idle : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_ready : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_ce0 : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_address1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_ce1 : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_we1 : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_idle : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_ready : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_ce0 : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_address1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_ce1 : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_we1 : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_d1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_find_largest_component_ccl_fu_168_ap_start : STD_LOGIC;
    signal grp_find_largest_component_ccl_fu_168_ap_done : STD_LOGIC;
    signal grp_find_largest_component_ccl_fu_168_ap_idle : STD_LOGIC;
    signal grp_find_largest_component_ccl_fu_168_ap_ready : STD_LOGIC;
    signal grp_find_largest_component_ccl_fu_168_binary_V_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_find_largest_component_ccl_fu_168_binary_V_ce0 : STD_LOGIC;
    signal grp_find_largest_component_ccl_fu_168_ap_return_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_find_largest_component_ccl_fu_168_ap_return_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_find_largest_component_ccl_fu_168_ap_return_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_find_largest_component_ccl_fu_168_ap_return_3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_find_largest_component_ccl_fu_168_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_find_largest_component_ccl_fu_168_ap_return_5 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_idle : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_ready : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out_ap_vld : STD_LOGIC;
    signal grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_ce0 : STD_LOGIC;
    signal ap_phi_mux_roi_count_1_phi_fu_142_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal roi_count_1_reg_138 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_find_largest_component_ccl_fu_168_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sub_ln231_fu_233_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln233_fu_239_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln231_1_fu_229_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln234_fu_243_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln230_1_fu_264_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln230_fu_270_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln231_fu_276_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln230_2_fu_267_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln233_fu_280_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln233_fu_283_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln233_1_fu_289_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln233_fu_303_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_464_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln234_fu_329_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sub_ln234_fu_332_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_cast_fu_338_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln234_fu_357_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln233_1_fu_373_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln233_1_fu_376_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln233_2_fu_386_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln233_1_fu_380_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln233_2_fu_389_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal roi_w_fu_393_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal roi_h_fu_404_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln235_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln233_fu_400_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal roi_w_1_fu_419_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln236_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln234_1_fu_409_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal roi_h_1_fu_437_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln233_3_fu_427_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln230_fu_370_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln234_fu_445_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_464_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_464_ce : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component card_recognizer_hw_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        trunc_ln : IN STD_LOGIC_VECTOR (30 downto 0);
        input_rgb_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        input_rgb_ce0 : OUT STD_LOGIC;
        input_rgb_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
        gray_V_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
        gray_V_ce1 : OUT STD_LOGIC;
        gray_V_we1 : OUT STD_LOGIC;
        gray_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component card_recognizer_hw_card_recognizer_hw_Pipeline_BINARIZE_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        trunc_ln : IN STD_LOGIC_VECTOR (30 downto 0);
        gray_V_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        gray_V_ce0 : OUT STD_LOGIC;
        gray_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        binary_V_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
        binary_V_ce1 : OUT STD_LOGIC;
        binary_V_we1 : OUT STD_LOGIC;
        binary_V_d1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component card_recognizer_hw_find_largest_component_ccl IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        height : IN STD_LOGIC_VECTOR (31 downto 0);
        binary_V_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        binary_V_ce0 : OUT STD_LOGIC;
        binary_V_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component card_recognizer_hw_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        card_box_min_y_V : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln246_1 : IN STD_LOGIC_VECTOR (8 downto 0);
        trunc_ln9 : IN STD_LOGIC_VECTOR (14 downto 0);
        card_box_min_x_V : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln246 : IN STD_LOGIC_VECTOR (9 downto 0);
        roi_count_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        roi_count_2_out_ap_vld : OUT STD_LOGIC;
        binary_V_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        binary_V_ce0 : OUT STD_LOGIC;
        binary_V_q0 : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component card_recognizer_hw_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component card_recognizer_hw_mul_mul_10s_11ns_22_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component card_recognizer_hw_gray_V_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component card_recognizer_hw_binary_V_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        address1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component card_recognizer_hw_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        result_rank : IN STD_LOGIC_VECTOR (31 downto 0);
        result_rank_ap_vld : IN STD_LOGIC;
        result_suit : IN STD_LOGIC_VECTOR (31 downto 0);
        result_suit_ap_vld : IN STD_LOGIC;
        width : OUT STD_LOGIC_VECTOR (31 downto 0);
        height : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    gray_V_U : component card_recognizer_hw_gray_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 19200,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_address0,
        ce0 => gray_V_ce0,
        q0 => gray_V_q0,
        address1 => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_address1,
        ce1 => gray_V_ce1,
        we1 => gray_V_we1,
        d1 => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_d1);

    binary_V_U : component card_recognizer_hw_binary_V_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 19200,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => binary_V_address0,
        ce0 => binary_V_ce0,
        q0 => binary_V_q0,
        address1 => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_address1,
        ce1 => binary_V_ce1,
        we1 => binary_V_we1,
        d1 => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_d1);

    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150 : component card_recognizer_hw_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start,
        ap_done => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done,
        ap_idle => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_idle,
        ap_ready => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_ready,
        trunc_ln => trunc_ln33_reg_500,
        input_rgb_address0 => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_address0,
        input_rgb_ce0 => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_ce0,
        input_rgb_q0 => input_rgb_q0,
        gray_V_address1 => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_address1,
        gray_V_ce1 => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_ce1,
        gray_V_we1 => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_we1,
        gray_V_d1 => grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_d1);

    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159 : component card_recognizer_hw_card_recognizer_hw_Pipeline_BINARIZE_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start,
        ap_done => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done,
        ap_idle => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_idle,
        ap_ready => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_ready,
        trunc_ln => trunc_ln33_reg_500,
        gray_V_address0 => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_address0,
        gray_V_ce0 => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_ce0,
        gray_V_q0 => gray_V_q0,
        binary_V_address1 => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_address1,
        binary_V_ce1 => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_ce1,
        binary_V_we1 => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_we1,
        binary_V_d1 => grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_d1);

    grp_find_largest_component_ccl_fu_168 : component card_recognizer_hw_find_largest_component_ccl
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_find_largest_component_ccl_fu_168_ap_start,
        ap_done => grp_find_largest_component_ccl_fu_168_ap_done,
        ap_idle => grp_find_largest_component_ccl_fu_168_ap_idle,
        ap_ready => grp_find_largest_component_ccl_fu_168_ap_ready,
        width => width_read_reg_478,
        height => height_read_reg_472,
        binary_V_address0 => grp_find_largest_component_ccl_fu_168_binary_V_address0,
        binary_V_ce0 => grp_find_largest_component_ccl_fu_168_binary_V_ce0,
        binary_V_q0 => binary_V_q0,
        ap_return_0 => grp_find_largest_component_ccl_fu_168_ap_return_0,
        ap_return_1 => grp_find_largest_component_ccl_fu_168_ap_return_1,
        ap_return_2 => grp_find_largest_component_ccl_fu_168_ap_return_2,
        ap_return_3 => grp_find_largest_component_ccl_fu_168_ap_return_3,
        ap_return_4 => grp_find_largest_component_ccl_fu_168_ap_return_4,
        ap_return_5 => grp_find_largest_component_ccl_fu_168_ap_return_5);

    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176 : component card_recognizer_hw_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start,
        ap_done => grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done,
        ap_idle => grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_idle,
        ap_ready => grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_ready,
        card_box_min_y_V => card_box_min_y_V_reg_513,
        zext_ln246_1 => y1_reg_584,
        trunc_ln9 => trunc_ln246_reg_549,
        card_box_min_x_V => card_box_min_x_V_reg_506,
        zext_ln246 => x1_reg_579,
        roi_count_2_out => grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out,
        roi_count_2_out_ap_vld => grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out_ap_vld,
        binary_V_address0 => grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_address0,
        binary_V_ce0 => grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_ce0,
        binary_V_q0 => binary_V_q0);

    control_s_axi_U : component card_recognizer_hw_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        result_rank => card_box_count_reg_524,
        result_rank_ap_vld => result_rank_ap_vld,
        result_suit => ap_phi_mux_roi_count_1_phi_fu_142_p4,
        result_suit_ap_vld => result_suit_ap_vld,
        width => width,
        height => height,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_32s_32s_32_2_1_U78 : component card_recognizer_hw_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => height_read_reg_472,
        din1 => width_read_reg_478,
        ce => ap_const_logic_1,
        dout => grp_fu_188_p2);

    mul_mul_10s_11ns_22_4_1_U79 : component card_recognizer_hw_mul_mul_10s_11ns_22_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 10,
        din1_WIDTH => 11,
        dout_WIDTH => 22)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => add_ln234_fu_243_p2,
        din1 => grp_fu_464_p1,
        ce => grp_fu_464_ce,
        dout => grp_fu_464_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_ready = ap_const_logic_1)) then 
                    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln33_fu_192_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_ready = ap_const_logic_1)) then 
                    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_ready = ap_const_logic_1)) then 
                    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_find_largest_component_ccl_fu_168_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_find_largest_component_ccl_fu_168_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_find_largest_component_ccl_fu_168_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_find_largest_component_ccl_fu_168_ap_ready = ap_const_logic_1)) then 
                    grp_find_largest_component_ccl_fu_168_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    roi_count_1_reg_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_find_largest_component_ccl_fu_168_ap_done = ap_const_logic_1) and (card_box_valid_V_fu_221_p1 = ap_const_lv1_0))) then 
                roi_count_1_reg_138 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state16) and (card_box_valid_V_reg_529 = ap_const_lv1_1))) then 
                roi_count_1_reg_138 <= grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                card_box_count_reg_524 <= grp_find_largest_component_ccl_fu_168_ap_return_4;
                card_box_max_x_V_reg_518 <= grp_find_largest_component_ccl_fu_168_ap_return_2;
                card_box_min_x_V_reg_506 <= grp_find_largest_component_ccl_fu_168_ap_return_0;
                card_box_min_y_V_reg_513 <= grp_find_largest_component_ccl_fu_168_ap_return_1;
                card_box_valid_V_reg_529 <= grp_find_largest_component_ccl_fu_168_ap_return_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                height_read_reg_472 <= height;
                width_read_reg_478 <= width;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                n_reg_491 <= grp_fu_188_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_2_reg_543 = ap_const_lv1_1))) then
                sub_ln234_1_reg_574 <= sub_ln234_1_fu_364_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                tmp_1_cast_reg_569 <= grp_fu_464_p2(19 downto 12);
                tmp_reg_554 <= add_ln233_fu_283_p2(9 downto 9);
                trunc_ln233_1_reg_559 <= sub_ln233_fu_303_p2(8 downto 2);
                trunc_ln233_2_reg_564 <= add_ln233_fu_283_p2(9 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (card_box_valid_V_fu_221_p1 = ap_const_lv1_1))) then
                tmp_2_reg_543 <= add_ln234_fu_243_p2(9 downto 9);
                trunc_ln246_reg_549 <= trunc_ln246_fu_261_p1;
                    zext_ln231_reg_533(7 downto 0) <= zext_ln231_fu_225_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln33_fu_192_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                trunc_ln33_reg_500 <= trunc_ln33_fu_197_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                x1_reg_579 <= x1_fu_449_p2;
                y1_reg_584 <= y1_fu_455_p2;
            end if;
        end if;
    end process;
    zext_ln231_reg_533(8) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln33_fu_192_p2, ap_CS_fsm_state9, card_box_valid_V_fu_221_p1, grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done, grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done, grp_find_largest_component_ccl_fu_168_ap_done, grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state15)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln33_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_find_largest_component_ccl_fu_168_ap_done = ap_const_logic_1) and (card_box_valid_V_fu_221_p1 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_find_largest_component_ccl_fu_168_ap_done = ap_const_logic_1) and (card_box_valid_V_fu_221_p1 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state15) and (grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln233_1_fu_289_p2 <= std_logic_vector(signed(sub_ln230_fu_270_p2) + signed(zext_ln233_fu_280_p1));
    add_ln233_fu_283_p2 <= std_logic_vector(signed(sext_ln231_fu_276_p1) + signed(zext_ln230_2_fu_267_p1));
    add_ln234_fu_243_p2 <= std_logic_vector(signed(sext_ln233_fu_239_p1) + signed(zext_ln231_1_fu_229_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;

    ap_ST_fsm_state15_blk_assign_proc : process(grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done)
    begin
        if ((grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state15_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state15_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done)
    begin
        if ((grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done)
    begin
        if ((grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_find_largest_component_ccl_fu_168_ap_done)
    begin
        if ((grp_find_largest_component_ccl_fu_168_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_roi_count_1_phi_fu_142_p4_assign_proc : process(card_box_valid_V_reg_529, grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out, roi_count_1_reg_138, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) and (card_box_valid_V_reg_529 = ap_const_lv1_1))) then 
            ap_phi_mux_roi_count_1_phi_fu_142_p4 <= grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out;
        else 
            ap_phi_mux_roi_count_1_phi_fu_142_p4 <= roi_count_1_reg_138;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    binary_V_address0_assign_proc : process(ap_CS_fsm_state9, grp_find_largest_component_ccl_fu_168_binary_V_address0, grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_address0, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            binary_V_address0 <= grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            binary_V_address0 <= grp_find_largest_component_ccl_fu_168_binary_V_address0;
        else 
            binary_V_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    binary_V_ce0_assign_proc : process(ap_CS_fsm_state9, grp_find_largest_component_ccl_fu_168_binary_V_ce0, grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_ce0, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            binary_V_ce0 <= grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            binary_V_ce0 <= grp_find_largest_component_ccl_fu_168_binary_V_ce0;
        else 
            binary_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    binary_V_ce1_assign_proc : process(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_ce1, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            binary_V_ce1 <= grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_ce1;
        else 
            binary_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    binary_V_we1_assign_proc : process(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_we1, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            binary_V_we1 <= grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_we1;
        else 
            binary_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    card_box_valid_V_fu_221_p1 <= grp_find_largest_component_ccl_fu_168_ap_return_5;

    gray_V_ce0_assign_proc : process(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_ce0, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            gray_V_ce0 <= grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_ce0;
        else 
            gray_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    gray_V_ce1_assign_proc : process(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            gray_V_ce1 <= grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_ce1;
        else 
            gray_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    gray_V_we1_assign_proc : process(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_we1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            gray_V_we1 <= grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_we1;
        else 
            gray_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start <= grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg;
    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start <= grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg;
    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start <= grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg;
    grp_find_largest_component_ccl_fu_168_ap_start <= grp_find_largest_component_ccl_fu_168_ap_start_reg;

    grp_fu_464_ce_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state12, grp_find_largest_component_ccl_fu_168_ap_done, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_find_largest_component_ccl_fu_168_ap_done = ap_const_logic_1)))) then 
            grp_fu_464_ce <= ap_const_logic_1;
        else 
            grp_fu_464_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_464_p1 <= ap_const_lv22_556(11 - 1 downto 0);
    icmp_ln235_fu_413_p2 <= "1" when (signed(roi_w_fu_393_p3) < signed(ap_const_lv10_1)) else "0";
    icmp_ln236_fu_431_p2 <= "1" when (signed(roi_h_fu_404_p3) < signed(ap_const_lv8_1)) else "0";
    icmp_ln33_fu_192_p2 <= "1" when (signed(n_reg_491) > signed(ap_const_lv32_0)) else "0";
    input_rgb_address0 <= grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_address0;
    input_rgb_ce0 <= grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_ce0;

    result_rank_ap_vld_assign_proc : process(ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            result_rank_ap_vld <= ap_const_logic_1;
        else 
            result_rank_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    result_suit_ap_vld_assign_proc : process(ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            result_suit_ap_vld <= ap_const_logic_1;
        else 
            result_suit_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    roi_h_1_fu_437_p3 <= 
        ap_const_lv7_1 when (icmp_ln236_fu_431_p2(0) = '1') else 
        trunc_ln234_1_fu_409_p1;
    roi_h_fu_404_p3 <= 
        sub_ln234_1_reg_574 when (tmp_2_reg_543(0) = '1') else 
        tmp_1_cast_reg_569;
    roi_w_1_fu_419_p3 <= 
        ap_const_lv9_1 when (icmp_ln235_fu_413_p2(0) = '1') else 
        trunc_ln233_fu_400_p1;
    roi_w_fu_393_p3 <= 
        sub_ln233_1_fu_380_p2 when (tmp_reg_554(0) = '1') else 
        zext_ln233_2_fu_389_p1;
    select_ln234_fu_357_p3 <= 
        tmp_cast_fu_338_p4 when (tmp_2_reg_543(0) = '1') else 
        tmp_1_cast_fu_348_p4;
        sext_ln231_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln230_fu_270_p2),10));

        sext_ln233_1_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln233_1_reg_559),9));

        sext_ln233_2_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln233_2_reg_564),9));

        sext_ln233_fu_239_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln231_fu_233_p2),10));

    sub_ln230_fu_270_p2 <= std_logic_vector(unsigned(ap_const_lv9_1) - unsigned(zext_ln230_1_fu_264_p1));
    sub_ln231_fu_233_p2 <= std_logic_vector(unsigned(ap_const_lv9_1) - unsigned(zext_ln231_fu_225_p1));
    sub_ln233_1_fu_380_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(zext_ln233_1_fu_376_p1));
    sub_ln233_fu_303_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(add_ln233_1_fu_289_p2));
    sub_ln234_1_fu_364_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(select_ln234_fu_357_p3));
    sub_ln234_fu_332_p2 <= std_logic_vector(unsigned(ap_const_lv20_0) - unsigned(trunc_ln234_fu_329_p1));
    tmp_1_cast_fu_348_p4 <= grp_fu_464_p2(19 downto 12);
    tmp_cast_fu_338_p4 <= sub_ln234_fu_332_p2(19 downto 12);
    trunc_ln233_fu_400_p1 <= roi_w_fu_393_p3(9 - 1 downto 0);
    trunc_ln234_1_fu_409_p1 <= roi_h_fu_404_p3(7 - 1 downto 0);
    trunc_ln234_fu_329_p1 <= grp_fu_464_p2(20 - 1 downto 0);
    trunc_ln246_fu_261_p1 <= width_read_reg_478(15 - 1 downto 0);
    trunc_ln33_fu_197_p1 <= n_reg_491(31 - 1 downto 0);
    x1_fu_449_p2 <= std_logic_vector(unsigned(zext_ln233_3_fu_427_p1) + unsigned(zext_ln230_fu_370_p1));
    y1_fu_455_p2 <= std_logic_vector(unsigned(zext_ln234_fu_445_p1) + unsigned(zext_ln231_reg_533));
    zext_ln230_1_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(card_box_min_x_V_reg_506),9));
    zext_ln230_2_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(card_box_max_x_V_reg_518),10));
    zext_ln230_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(card_box_min_x_V_reg_506),10));
    zext_ln231_1_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_find_largest_component_ccl_fu_168_ap_return_3),10));
    zext_ln231_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_find_largest_component_ccl_fu_168_ap_return_1),9));
    zext_ln233_1_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln233_1_fu_373_p1),10));
    zext_ln233_2_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln233_2_fu_386_p1),10));
    zext_ln233_3_fu_427_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(roi_w_1_fu_419_p3),10));
    zext_ln233_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(card_box_max_x_V_reg_518),9));
    zext_ln234_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(roi_h_1_fu_437_p3),9));
end behav;
