// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module card_recognizer_hw_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        trunc_ln,
        input_rgb_address0,
        input_rgb_ce0,
        input_rgb_q0,
        gray_V_address1,
        gray_V_ce1,
        gray_V_we1,
        gray_V_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [30:0] trunc_ln;
output  [14:0] input_rgb_address0;
output   input_rgb_ce0;
input  [23:0] input_rgb_q0;
output  [14:0] gray_V_address1;
output   gray_V_ce1;
output   gray_V_we1;
output  [7:0] gray_V_d1;

reg ap_idle;
reg input_rgb_ce0;
reg gray_V_ce1;
reg gray_V_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln33_fu_118_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln33_fu_130_p1;
reg   [63:0] zext_ln33_reg_222;
reg   [63:0] zext_ln33_reg_222_pp0_iter1_reg;
reg   [63:0] zext_ln33_reg_222_pp0_iter2_reg;
reg   [63:0] zext_ln33_reg_222_pp0_iter3_reg;
reg   [63:0] zext_ln33_reg_222_pp0_iter4_reg;
wire   [7:0] r_fu_140_p1;
reg   [7:0] r_reg_232;
reg   [7:0] r_reg_232_pp0_iter2_reg;
reg   [7:0] g_reg_237;
wire   [14:0] mul_ln40_fu_174_p2;
wire    ap_block_pp0_stage0;
reg   [14:0] i_fu_66;
wire   [14:0] add_ln33_fu_124_p2;
wire    ap_loop_init;
reg   [14:0] ap_sig_allocacmp_i_3;
wire   [30:0] zext_ln33_1_fu_114_p1;
wire   [7:0] b_fu_154_p4;
wire   [7:0] mul_ln40_fu_174_p0;
wire   [7:0] mul_ln40_fu_174_p1;
wire   [14:0] grp_fu_193_p3;
wire   [15:0] grp_fu_202_p3;
wire   [7:0] grp_fu_193_p0;
wire   [4:0] grp_fu_193_p1;
wire   [7:0] grp_fu_202_p0;
wire   [7:0] grp_fu_202_p1;
wire   [14:0] grp_fu_202_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [12:0] grp_fu_193_p00;
wire   [15:0] grp_fu_202_p00;
wire   [15:0] grp_fu_202_p20;
wire   [14:0] mul_ln40_fu_174_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

card_recognizer_hw_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U1(
    .din0(mul_ln40_fu_174_p0),
    .din1(mul_ln40_fu_174_p1),
    .dout(mul_ln40_fu_174_p2)
);

card_recognizer_hw_mac_muladd_8ns_5ns_15ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_5ns_15ns_15_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_193_p0),
    .din1(grp_fu_193_p1),
    .din2(mul_ln40_fu_174_p2),
    .ce(1'b1),
    .dout(grp_fu_193_p3)
);

card_recognizer_hw_mac_muladd_8ns_8ns_15ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_15ns_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_202_p0),
    .din1(grp_fu_202_p1),
    .din2(grp_fu_202_p2),
    .ce(1'b1),
    .dout(grp_fu_202_p3)
);

card_recognizer_hw_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln33_fu_118_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_66 <= add_ln33_fu_124_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_66 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        g_reg_237 <= {{input_rgb_q0[15:8]}};
        r_reg_232 <= r_fu_140_p1;
        zext_ln33_reg_222_pp0_iter1_reg[14 : 0] <= zext_ln33_reg_222[14 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        r_reg_232_pp0_iter2_reg <= r_reg_232;
        zext_ln33_reg_222_pp0_iter2_reg[14 : 0] <= zext_ln33_reg_222_pp0_iter1_reg[14 : 0];
        zext_ln33_reg_222_pp0_iter3_reg[14 : 0] <= zext_ln33_reg_222_pp0_iter2_reg[14 : 0];
        zext_ln33_reg_222_pp0_iter4_reg[14 : 0] <= zext_ln33_reg_222_pp0_iter3_reg[14 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln33_fu_118_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln33_reg_222[14 : 0] <= zext_ln33_fu_130_p1[14 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_118_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 15'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        gray_V_ce1 = 1'b1;
    end else begin
        gray_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        gray_V_we1 = 1'b1;
    end else begin
        gray_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_rgb_ce0 = 1'b1;
    end else begin
        input_rgb_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln33_fu_124_p2 = (ap_sig_allocacmp_i_3 + 15'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_fu_154_p4 = {{input_rgb_q0[23:16]}};

assign gray_V_address1 = zext_ln33_reg_222_pp0_iter4_reg;

assign gray_V_d1 = {{grp_fu_202_p3[15:8]}};

assign grp_fu_193_p0 = grp_fu_193_p00;

assign grp_fu_193_p00 = b_fu_154_p4;

assign grp_fu_193_p1 = 13'd29;

assign grp_fu_202_p0 = grp_fu_202_p00;

assign grp_fu_202_p00 = g_reg_237;

assign grp_fu_202_p1 = 16'd150;

assign grp_fu_202_p2 = grp_fu_202_p20;

assign grp_fu_202_p20 = grp_fu_193_p3;

assign icmp_ln33_fu_118_p2 = ((zext_ln33_1_fu_114_p1 == trunc_ln) ? 1'b1 : 1'b0);

assign input_rgb_address0 = zext_ln33_fu_130_p1;

assign mul_ln40_fu_174_p0 = mul_ln40_fu_174_p00;

assign mul_ln40_fu_174_p00 = r_reg_232_pp0_iter2_reg;

assign mul_ln40_fu_174_p1 = 15'd77;

assign r_fu_140_p1 = input_rgb_q0[7:0];

assign zext_ln33_1_fu_114_p1 = ap_sig_allocacmp_i_3;

assign zext_ln33_fu_130_p1 = ap_sig_allocacmp_i_3;

always @ (posedge ap_clk) begin
    zext_ln33_reg_222[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln33_reg_222_pp0_iter1_reg[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln33_reg_222_pp0_iter2_reg[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln33_reg_222_pp0_iter3_reg[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln33_reg_222_pp0_iter4_reg[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
end

endmodule //card_recognizer_hw_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP
