// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module card_recognizer_hw_find_largest_component_ccl_Pipeline_CLEAR_CURR_ROW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        curr_label_V_1_address0,
        curr_label_V_1_ce0,
        curr_label_V_1_we0,
        curr_label_V_1_d0,
        curr_label_V_address0,
        curr_label_V_ce0,
        curr_label_V_we0,
        curr_label_V_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] curr_label_V_1_address0;
output   curr_label_V_1_ce0;
output   curr_label_V_1_we0;
output  [7:0] curr_label_V_1_d0;
output  [6:0] curr_label_V_address0;
output   curr_label_V_ce0;
output   curr_label_V_we0;
output  [7:0] curr_label_V_d0;

reg ap_idle;
reg curr_label_V_1_ce0;
reg curr_label_V_1_we0;
reg curr_label_V_ce0;
reg curr_label_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln130_fu_72_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln133_fu_94_p1;
reg   [7:0] x_1_fu_32;
wire   [7:0] add_ln130_fu_78_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_x;
wire   [0:0] trunc_ln133_fu_100_p1;
wire   [6:0] lshr_ln1_fu_84_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

card_recognizer_hw_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln130_fu_72_p2 == 1'd0)) begin
            x_1_fu_32 <= add_ln130_fu_78_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_1_fu_32 <= 8'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln130_fu_72_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_x = 8'd0;
    end else begin
        ap_sig_allocacmp_x = x_1_fu_32;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        curr_label_V_1_ce0 = 1'b1;
    end else begin
        curr_label_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln133_fu_100_p1 == 1'd1) & (icmp_ln130_fu_72_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        curr_label_V_1_we0 = 1'b1;
    end else begin
        curr_label_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        curr_label_V_ce0 = 1'b1;
    end else begin
        curr_label_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln133_fu_100_p1 == 1'd0) & (icmp_ln130_fu_72_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        curr_label_V_we0 = 1'b1;
    end else begin
        curr_label_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln130_fu_78_p2 = (ap_sig_allocacmp_x + 8'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign curr_label_V_1_address0 = zext_ln133_fu_94_p1;

assign curr_label_V_1_d0 = 8'd0;

assign curr_label_V_address0 = zext_ln133_fu_94_p1;

assign curr_label_V_d0 = 8'd0;

assign icmp_ln130_fu_72_p2 = ((ap_sig_allocacmp_x == 8'd160) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_84_p4 = {{ap_sig_allocacmp_x[7:1]}};

assign trunc_ln133_fu_100_p1 = ap_sig_allocacmp_x[0:0];

assign zext_ln133_fu_94_p1 = lshr_ln1_fu_84_p4;

endmodule //card_recognizer_hw_find_largest_component_ccl_Pipeline_CLEAR_CURR_ROW
