// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module card_recognizer_hw_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        card_box_min_y_V,
        zext_ln246_1,
        trunc_ln9,
        card_box_min_x_V,
        zext_ln246,
        roi_count_2_out,
        roi_count_2_out_ap_vld,
        binary_V_address0,
        binary_V_ce0,
        binary_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] card_box_min_y_V;
input  [8:0] zext_ln246_1;
input  [14:0] trunc_ln9;
input  [7:0] card_box_min_x_V;
input  [9:0] zext_ln246;
output  [31:0] roi_count_2_out;
output   roi_count_2_out_ap_vld;
output  [14:0] binary_V_address0;
output   binary_V_ce0;
input  [0:0] binary_V_q0;

reg ap_idle;
reg roi_count_2_out_ap_vld;
reg binary_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln246_fu_194_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln246_reg_419;
reg   [0:0] icmp_ln246_reg_419_pp0_iter1_reg;
reg   [0:0] icmp_ln246_reg_419_pp0_iter2_reg;
wire   [7:0] select_ln246_fu_215_p3;
reg   [7:0] select_ln246_reg_423;
reg   [7:0] select_ln246_reg_423_pp0_iter1_reg;
wire   [0:0] and_ln252_1_fu_309_p2;
reg   [0:0] and_ln252_1_reg_433;
reg   [0:0] and_ln252_1_reg_433_pp0_iter1_reg;
reg   [0:0] and_ln252_1_reg_433_pp0_iter2_reg;
reg   [0:0] and_ln252_1_reg_433_pp0_iter3_reg;
wire   [63:0] zext_ln541_fu_339_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] roi_count_1_fu_70;
wire   [31:0] roi_count_fu_360_p3;
wire    ap_loop_init;
reg   [7:0] x_fu_74;
wire   [7:0] add_ln249_fu_315_p2;
reg   [7:0] ap_sig_allocacmp_x_load;
reg   [6:0] y_fu_78;
wire   [6:0] select_ln246_1_fu_237_p3;
reg   [6:0] ap_sig_allocacmp_y_2;
reg   [14:0] indvar_flatten_fu_82;
wire   [14:0] add_ln246_fu_200_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] zext_ln246_3_fu_166_p1;
wire   [0:0] ult_fu_170_p2;
wire   [8:0] zext_ln246_2_fu_162_p1;
wire   [0:0] notrhs_fu_182_p2;
wire   [0:0] rev20_fu_176_p2;
wire   [0:0] icmp_ln249_fu_209_p2;
wire   [6:0] add_ln246_1_fu_223_p2;
wire   [7:0] zext_ln246_5_fu_233_p1;
wire   [0:0] ult21_fu_249_p2;
wire   [8:0] zext_ln246_4_fu_229_p1;
wire   [0:0] notrhs_mid1_fu_261_p2;
wire   [0:0] rev22_fu_255_p2;
wire   [0:0] and_ln252_3_fu_267_p2;
wire   [0:0] and_ln252_fu_188_p2;
wire   [0:0] icmp_ln252_fu_285_p2;
wire   [9:0] zext_ln251_fu_281_p1;
wire   [0:0] xor_ln252_fu_291_p2;
wire   [0:0] icmp_ln252_1_fu_297_p2;
wire   [0:0] and_ln252_2_fu_303_p2;
wire   [0:0] select_ln246_2_fu_273_p3;
wire  signed [14:0] zext_ln541_fu_339_p0;
wire   [14:0] grp_fu_376_p3;
wire   [31:0] add_ln255_fu_346_p2;
wire   [31:0] roi_count_2_fu_352_p3;
wire   [6:0] grp_fu_376_p0;
wire   [7:0] grp_fu_376_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [14:0] grp_fu_376_p00;
wire   [14:0] grp_fu_376_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

card_recognizer_hw_mac_muladd_7ns_15s_8ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mac_muladd_7ns_15s_8ns_15_4_1_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_376_p0),
    .din1(trunc_ln9),
    .din2(grp_fu_376_p2),
    .ce(1'b1),
    .dout(grp_fu_376_p3)
);

card_recognizer_hw_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln246_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_82 <= add_ln246_fu_200_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            roi_count_1_fu_70 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            roi_count_1_fu_70 <= roi_count_fu_360_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln246_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_74 <= add_ln249_fu_315_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_74 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln246_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_78 <= select_ln246_1_fu_237_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_78 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln246_fu_194_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln252_1_reg_433 <= and_ln252_1_fu_309_p2;
        select_ln246_reg_423 <= select_ln246_fu_215_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln252_1_reg_433_pp0_iter1_reg <= and_ln252_1_reg_433;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln246_reg_419 <= icmp_ln246_fu_194_p2;
        icmp_ln246_reg_419_pp0_iter1_reg <= icmp_ln246_reg_419;
        select_ln246_reg_423_pp0_iter1_reg <= select_ln246_reg_423;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln252_1_reg_433_pp0_iter2_reg <= and_ln252_1_reg_433_pp0_iter1_reg;
        and_ln252_1_reg_433_pp0_iter3_reg <= and_ln252_1_reg_433_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln246_reg_419_pp0_iter2_reg <= icmp_ln246_reg_419_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((icmp_ln246_fu_194_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_load = 8'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_y_2 = y_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        binary_V_ce0 = 1'b1;
    end else begin
        binary_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln246_reg_419_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        roi_count_2_out_ap_vld = 1'b1;
    end else begin
        roi_count_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln246_1_fu_223_p2 = (ap_sig_allocacmp_y_2 + 7'd1);

assign add_ln246_fu_200_p2 = (ap_sig_allocacmp_indvar_flatten_load + 15'd1);

assign add_ln249_fu_315_p2 = (select_ln246_fu_215_p3 + 8'd1);

assign add_ln255_fu_346_p2 = (roi_count_1_fu_70 + 32'd1);

assign and_ln252_1_fu_309_p2 = (select_ln246_2_fu_273_p3 & and_ln252_2_fu_303_p2);

assign and_ln252_2_fu_303_p2 = (xor_ln252_fu_291_p2 & icmp_ln252_1_fu_297_p2);

assign and_ln252_3_fu_267_p2 = (rev22_fu_255_p2 & notrhs_mid1_fu_261_p2);

assign and_ln252_fu_188_p2 = (rev20_fu_176_p2 & notrhs_fu_182_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign binary_V_address0 = zext_ln541_fu_339_p1;

assign grp_fu_376_p0 = grp_fu_376_p00;

assign grp_fu_376_p00 = select_ln246_1_fu_237_p3;

assign grp_fu_376_p2 = grp_fu_376_p20;

assign grp_fu_376_p20 = select_ln246_reg_423_pp0_iter1_reg;

assign icmp_ln246_fu_194_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 15'd19200) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_209_p2 = ((ap_sig_allocacmp_x_load == 8'd160) ? 1'b1 : 1'b0);

assign icmp_ln252_1_fu_297_p2 = ((zext_ln251_fu_281_p1 < zext_ln246) ? 1'b1 : 1'b0);

assign icmp_ln252_fu_285_p2 = ((select_ln246_fu_215_p3 < card_box_min_x_V) ? 1'b1 : 1'b0);

assign notrhs_fu_182_p2 = ((zext_ln246_2_fu_162_p1 < zext_ln246_1) ? 1'b1 : 1'b0);

assign notrhs_mid1_fu_261_p2 = ((zext_ln246_4_fu_229_p1 < zext_ln246_1) ? 1'b1 : 1'b0);

assign rev20_fu_176_p2 = (ult_fu_170_p2 ^ 1'd1);

assign rev22_fu_255_p2 = (ult21_fu_249_p2 ^ 1'd1);

assign roi_count_2_fu_352_p3 = ((binary_V_q0[0:0] == 1'b1) ? add_ln255_fu_346_p2 : roi_count_1_fu_70);

assign roi_count_2_out = roi_count_1_fu_70;

assign roi_count_fu_360_p3 = ((and_ln252_1_reg_433_pp0_iter3_reg[0:0] == 1'b1) ? roi_count_2_fu_352_p3 : roi_count_1_fu_70);

assign select_ln246_1_fu_237_p3 = ((icmp_ln249_fu_209_p2[0:0] == 1'b1) ? add_ln246_1_fu_223_p2 : ap_sig_allocacmp_y_2);

assign select_ln246_2_fu_273_p3 = ((icmp_ln249_fu_209_p2[0:0] == 1'b1) ? and_ln252_3_fu_267_p2 : and_ln252_fu_188_p2);

assign select_ln246_fu_215_p3 = ((icmp_ln249_fu_209_p2[0:0] == 1'b1) ? 8'd0 : ap_sig_allocacmp_x_load);

assign ult21_fu_249_p2 = ((zext_ln246_5_fu_233_p1 < card_box_min_y_V) ? 1'b1 : 1'b0);

assign ult_fu_170_p2 = ((zext_ln246_3_fu_166_p1 < card_box_min_y_V) ? 1'b1 : 1'b0);

assign xor_ln252_fu_291_p2 = (icmp_ln252_fu_285_p2 ^ 1'd1);

assign zext_ln246_2_fu_162_p1 = ap_sig_allocacmp_y_2;

assign zext_ln246_3_fu_166_p1 = ap_sig_allocacmp_y_2;

assign zext_ln246_4_fu_229_p1 = add_ln246_1_fu_223_p2;

assign zext_ln246_5_fu_233_p1 = add_ln246_1_fu_223_p2;

assign zext_ln251_fu_281_p1 = select_ln246_fu_215_p3;

assign zext_ln541_fu_339_p0 = grp_fu_376_p3;

assign zext_ln541_fu_339_p1 = $unsigned(zext_ln541_fu_339_p0);

endmodule //card_recognizer_hw_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP
