// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="card_recognizer_hw_card_recognizer_hw,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010i-clg225-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.164000,HLS_SYN_LAT=300658,HLS_SYN_TPT=none,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=1895,HLS_SYN_LUT=3886,HLS_VERSION=2022_2}" *)

module card_recognizer_hw (
        ap_clk,
        ap_rst_n,
        input_rgb_address0,
        input_rgb_ce0,
        input_rgb_q0,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [14:0] input_rgb_address0;
output   input_rgb_ce0;
input  [23:0] input_rgb_q0;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg    result_rank_ap_vld;
reg    result_suit_ap_vld;
wire   [31:0] width;
wire   [31:0] height;
reg    gray_V_ce0;
wire   [7:0] gray_V_q0;
reg    gray_V_ce1;
reg    gray_V_we1;
reg   [14:0] binary_V_address0;
reg    binary_V_ce0;
wire   [0:0] binary_V_q0;
reg    binary_V_ce1;
reg    binary_V_we1;
reg   [31:0] height_read_reg_472;
reg   [31:0] width_read_reg_478;
wire   [31:0] grp_fu_188_p2;
reg   [31:0] n_reg_491;
wire    ap_CS_fsm_state3;
wire   [30:0] trunc_ln33_fu_197_p1;
reg   [30:0] trunc_ln33_reg_500;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln33_fu_192_p2;
reg   [7:0] card_box_min_x_V_reg_506;
wire    ap_CS_fsm_state9;
reg   [7:0] card_box_min_y_V_reg_513;
reg   [7:0] card_box_max_x_V_reg_518;
reg   [31:0] card_box_count_reg_524;
wire   [0:0] card_box_valid_V_fu_221_p1;
reg   [0:0] card_box_valid_V_reg_529;
wire   [8:0] zext_ln231_fu_225_p1;
reg   [8:0] zext_ln231_reg_533;
reg   [0:0] tmp_2_reg_543;
wire   [14:0] trunc_ln246_fu_261_p1;
reg   [14:0] trunc_ln246_reg_549;
reg   [0:0] tmp_reg_554;
wire    ap_CS_fsm_state12;
reg   [6:0] trunc_ln233_1_reg_559;
reg   [7:0] trunc_ln233_2_reg_564;
wire   [7:0] tmp_1_cast_fu_348_p4;
reg   [7:0] tmp_1_cast_reg_569;
wire   [7:0] sub_ln234_1_fu_364_p2;
reg   [7:0] sub_ln234_1_reg_574;
wire   [9:0] x1_fu_449_p2;
reg   [9:0] x1_reg_579;
wire    ap_CS_fsm_state13;
wire   [8:0] y1_fu_455_p2;
reg   [8:0] y1_reg_584;
wire    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start;
wire    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done;
wire    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_idle;
wire    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_ready;
wire   [14:0] grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_address0;
wire    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_ce0;
wire   [14:0] grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_address1;
wire    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_ce1;
wire    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_we1;
wire   [7:0] grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_d1;
wire    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start;
wire    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done;
wire    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_idle;
wire    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_ready;
wire   [14:0] grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_address0;
wire    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_ce0;
wire   [14:0] grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_address1;
wire    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_ce1;
wire    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_we1;
wire   [0:0] grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_d1;
wire    grp_find_largest_component_ccl_fu_168_ap_start;
wire    grp_find_largest_component_ccl_fu_168_ap_done;
wire    grp_find_largest_component_ccl_fu_168_ap_idle;
wire    grp_find_largest_component_ccl_fu_168_ap_ready;
wire   [14:0] grp_find_largest_component_ccl_fu_168_binary_V_address0;
wire    grp_find_largest_component_ccl_fu_168_binary_V_ce0;
wire   [7:0] grp_find_largest_component_ccl_fu_168_ap_return_0;
wire   [7:0] grp_find_largest_component_ccl_fu_168_ap_return_1;
wire   [7:0] grp_find_largest_component_ccl_fu_168_ap_return_2;
wire   [7:0] grp_find_largest_component_ccl_fu_168_ap_return_3;
wire   [31:0] grp_find_largest_component_ccl_fu_168_ap_return_4;
wire   [0:0] grp_find_largest_component_ccl_fu_168_ap_return_5;
wire    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start;
wire    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done;
wire    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_idle;
wire    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_ready;
wire   [31:0] grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out;
wire    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out_ap_vld;
wire   [14:0] grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_address0;
wire    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_ce0;
reg   [31:0] ap_phi_mux_roi_count_1_phi_fu_142_p4;
reg   [31:0] roi_count_1_reg_138;
wire    ap_CS_fsm_state16;
reg    grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_find_largest_component_ccl_fu_168_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state2;
wire   [8:0] sub_ln231_fu_233_p2;
wire  signed [9:0] sext_ln233_fu_239_p1;
wire   [9:0] zext_ln231_1_fu_229_p1;
wire  signed [9:0] add_ln234_fu_243_p2;
wire   [8:0] zext_ln230_1_fu_264_p1;
wire  signed [8:0] sub_ln230_fu_270_p2;
wire  signed [9:0] sext_ln231_fu_276_p1;
wire   [9:0] zext_ln230_2_fu_267_p1;
wire   [8:0] zext_ln233_fu_280_p1;
wire   [9:0] add_ln233_fu_283_p2;
wire   [8:0] add_ln233_1_fu_289_p2;
wire   [8:0] sub_ln233_fu_303_p2;
wire  signed [21:0] grp_fu_464_p2;
wire   [19:0] trunc_ln234_fu_329_p1;
wire   [19:0] sub_ln234_fu_332_p2;
wire   [7:0] tmp_cast_fu_338_p4;
wire   [7:0] select_ln234_fu_357_p3;
wire  signed [8:0] sext_ln233_1_fu_373_p1;
wire   [9:0] zext_ln233_1_fu_376_p1;
wire  signed [8:0] sext_ln233_2_fu_386_p1;
wire   [9:0] sub_ln233_1_fu_380_p2;
wire   [9:0] zext_ln233_2_fu_389_p1;
wire   [9:0] roi_w_fu_393_p3;
wire   [7:0] roi_h_fu_404_p3;
wire   [0:0] icmp_ln235_fu_413_p2;
wire   [8:0] trunc_ln233_fu_400_p1;
wire   [8:0] roi_w_1_fu_419_p3;
wire   [0:0] icmp_ln236_fu_431_p2;
wire   [6:0] trunc_ln234_1_fu_409_p1;
wire   [6:0] roi_h_1_fu_437_p3;
wire   [9:0] zext_ln233_3_fu_427_p1;
wire   [9:0] zext_ln230_fu_370_p1;
wire   [8:0] zext_ln234_fu_445_p1;
wire   [10:0] grp_fu_464_p1;
reg    grp_fu_464_ce;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg = 1'b0;
#0 grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg = 1'b0;
#0 grp_find_largest_component_ccl_fu_168_ap_start_reg = 1'b0;
#0 grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg = 1'b0;
end

card_recognizer_hw_gray_V_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 19200 ),
    .AddressWidth( 15 ))
gray_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_address0),
    .ce0(gray_V_ce0),
    .q0(gray_V_q0),
    .address1(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_address1),
    .ce1(gray_V_ce1),
    .we1(gray_V_we1),
    .d1(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_d1)
);

card_recognizer_hw_binary_V_RAM_2P_BRAM_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 19200 ),
    .AddressWidth( 15 ))
binary_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(binary_V_address0),
    .ce0(binary_V_ce0),
    .q0(binary_V_q0),
    .address1(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_address1),
    .ce1(binary_V_ce1),
    .we1(binary_V_we1),
    .d1(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_d1)
);

card_recognizer_hw_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start),
    .ap_done(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done),
    .ap_idle(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_idle),
    .ap_ready(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_ready),
    .trunc_ln(trunc_ln33_reg_500),
    .input_rgb_address0(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_address0),
    .input_rgb_ce0(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_ce0),
    .input_rgb_q0(input_rgb_q0),
    .gray_V_address1(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_address1),
    .gray_V_ce1(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_ce1),
    .gray_V_we1(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_we1),
    .gray_V_d1(grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_d1)
);

card_recognizer_hw_card_recognizer_hw_Pipeline_BINARIZE_LOOP grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start),
    .ap_done(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done),
    .ap_idle(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_idle),
    .ap_ready(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_ready),
    .trunc_ln(trunc_ln33_reg_500),
    .gray_V_address0(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_address0),
    .gray_V_ce0(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_ce0),
    .gray_V_q0(gray_V_q0),
    .binary_V_address1(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_address1),
    .binary_V_ce1(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_ce1),
    .binary_V_we1(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_we1),
    .binary_V_d1(grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_d1)
);

card_recognizer_hw_find_largest_component_ccl grp_find_largest_component_ccl_fu_168(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_find_largest_component_ccl_fu_168_ap_start),
    .ap_done(grp_find_largest_component_ccl_fu_168_ap_done),
    .ap_idle(grp_find_largest_component_ccl_fu_168_ap_idle),
    .ap_ready(grp_find_largest_component_ccl_fu_168_ap_ready),
    .width(width_read_reg_478),
    .height(height_read_reg_472),
    .binary_V_address0(grp_find_largest_component_ccl_fu_168_binary_V_address0),
    .binary_V_ce0(grp_find_largest_component_ccl_fu_168_binary_V_ce0),
    .binary_V_q0(binary_V_q0),
    .ap_return_0(grp_find_largest_component_ccl_fu_168_ap_return_0),
    .ap_return_1(grp_find_largest_component_ccl_fu_168_ap_return_1),
    .ap_return_2(grp_find_largest_component_ccl_fu_168_ap_return_2),
    .ap_return_3(grp_find_largest_component_ccl_fu_168_ap_return_3),
    .ap_return_4(grp_find_largest_component_ccl_fu_168_ap_return_4),
    .ap_return_5(grp_find_largest_component_ccl_fu_168_ap_return_5)
);

card_recognizer_hw_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start),
    .ap_done(grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done),
    .ap_idle(grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_idle),
    .ap_ready(grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_ready),
    .card_box_min_y_V(card_box_min_y_V_reg_513),
    .zext_ln246_1(y1_reg_584),
    .trunc_ln9(trunc_ln246_reg_549),
    .card_box_min_x_V(card_box_min_x_V_reg_506),
    .zext_ln246(x1_reg_579),
    .roi_count_2_out(grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out),
    .roi_count_2_out_ap_vld(grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out_ap_vld),
    .binary_V_address0(grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_address0),
    .binary_V_ce0(grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_ce0),
    .binary_V_q0(binary_V_q0)
);

card_recognizer_hw_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .result_rank(card_box_count_reg_524),
    .result_rank_ap_vld(result_rank_ap_vld),
    .result_suit(ap_phi_mux_roi_count_1_phi_fu_142_p4),
    .result_suit_ap_vld(result_suit_ap_vld),
    .width(width),
    .height(height),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

card_recognizer_hw_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U78(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(height_read_reg_472),
    .din1(width_read_reg_478),
    .ce(1'b1),
    .dout(grp_fu_188_p2)
);

card_recognizer_hw_mul_mul_10s_11ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 22 ))
mul_mul_10s_11ns_22_4_1_U79(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(add_ln234_fu_243_p2),
    .din1(grp_fu_464_p1),
    .ce(grp_fu_464_ce),
    .dout(grp_fu_464_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg <= 1'b1;
        end else if ((grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_ready == 1'b1)) begin
            grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln33_fu_192_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg <= 1'b1;
        end else if ((grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_ready == 1'b1)) begin
            grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg <= 1'b1;
        end else if ((grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_ready == 1'b1)) begin
            grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_find_largest_component_ccl_fu_168_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_find_largest_component_ccl_fu_168_ap_start_reg <= 1'b1;
        end else if ((grp_find_largest_component_ccl_fu_168_ap_ready == 1'b1)) begin
            grp_find_largest_component_ccl_fu_168_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_find_largest_component_ccl_fu_168_ap_done == 1'b1) & (card_box_valid_V_fu_221_p1 == 1'd0))) begin
        roi_count_1_reg_138 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state16) & (card_box_valid_V_reg_529 == 1'd1))) begin
        roi_count_1_reg_138 <= grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        card_box_count_reg_524 <= grp_find_largest_component_ccl_fu_168_ap_return_4;
        card_box_max_x_V_reg_518 <= grp_find_largest_component_ccl_fu_168_ap_return_2;
        card_box_min_x_V_reg_506 <= grp_find_largest_component_ccl_fu_168_ap_return_0;
        card_box_min_y_V_reg_513 <= grp_find_largest_component_ccl_fu_168_ap_return_1;
        card_box_valid_V_reg_529 <= grp_find_largest_component_ccl_fu_168_ap_return_5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        height_read_reg_472 <= height;
        width_read_reg_478 <= width;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        n_reg_491 <= grp_fu_188_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (tmp_2_reg_543 == 1'd1))) begin
        sub_ln234_1_reg_574 <= sub_ln234_1_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_1_cast_reg_569 <= {{grp_fu_464_p2[19:12]}};
        tmp_reg_554 <= add_ln233_fu_283_p2[32'd9];
        trunc_ln233_1_reg_559 <= {{sub_ln233_fu_303_p2[8:2]}};
        trunc_ln233_2_reg_564 <= {{add_ln233_fu_283_p2[9:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (card_box_valid_V_fu_221_p1 == 1'd1))) begin
        tmp_2_reg_543 <= add_ln234_fu_243_p2[32'd9];
        trunc_ln246_reg_549 <= trunc_ln246_fu_261_p1;
        zext_ln231_reg_533[7 : 0] <= zext_ln231_fu_225_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln33_fu_192_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        trunc_ln33_reg_500 <= trunc_ln33_fu_197_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        x1_reg_579 <= x1_fu_449_p2;
        y1_reg_584 <= y1_fu_455_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_find_largest_component_ccl_fu_168_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (card_box_valid_V_reg_529 == 1'd1))) begin
        ap_phi_mux_roi_count_1_phi_fu_142_p4 = grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_roi_count_2_out;
    end else begin
        ap_phi_mux_roi_count_1_phi_fu_142_p4 = roi_count_1_reg_138;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        binary_V_address0 = grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        binary_V_address0 = grp_find_largest_component_ccl_fu_168_binary_V_address0;
    end else begin
        binary_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        binary_V_ce0 = grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_binary_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        binary_V_ce0 = grp_find_largest_component_ccl_fu_168_binary_V_ce0;
    end else begin
        binary_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        binary_V_ce1 = grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_ce1;
    end else begin
        binary_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        binary_V_we1 = grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_binary_V_we1;
    end else begin
        binary_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        gray_V_ce0 = grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_gray_V_ce0;
    end else begin
        gray_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        gray_V_ce1 = grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_ce1;
    end else begin
        gray_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        gray_V_we1 = grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_gray_V_we1;
    end else begin
        gray_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state9) & (grp_find_largest_component_ccl_fu_168_ap_done == 1'b1)))) begin
        grp_fu_464_ce = 1'b1;
    end else begin
        grp_fu_464_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        result_rank_ap_vld = 1'b1;
    end else begin
        result_rank_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        result_suit_ap_vld = 1'b1;
    end else begin
        result_suit_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln33_fu_192_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_find_largest_component_ccl_fu_168_ap_done == 1'b1) & (card_box_valid_V_fu_221_p1 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((1'b1 == ap_CS_fsm_state9) & (grp_find_largest_component_ccl_fu_168_ap_done == 1'b1) & (card_box_valid_V_fu_221_p1 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln233_1_fu_289_p2 = ($signed(sub_ln230_fu_270_p2) + $signed(zext_ln233_fu_280_p1));

assign add_ln233_fu_283_p2 = ($signed(sext_ln231_fu_276_p1) + $signed(zext_ln230_2_fu_267_p1));

assign add_ln234_fu_243_p2 = ($signed(sext_ln233_fu_239_p1) + $signed(zext_ln231_1_fu_229_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign card_box_valid_V_fu_221_p1 = grp_find_largest_component_ccl_fu_168_ap_return_5;

assign grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start = grp_card_recognizer_hw_Pipeline_BINARIZE_LOOP_fu_159_ap_start_reg;

assign grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start = grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_ap_start_reg;

assign grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start = grp_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP_fu_176_ap_start_reg;

assign grp_find_largest_component_ccl_fu_168_ap_start = grp_find_largest_component_ccl_fu_168_ap_start_reg;

assign grp_fu_464_p1 = 22'd1366;

assign icmp_ln235_fu_413_p2 = (($signed(roi_w_fu_393_p3) < $signed(10'd1)) ? 1'b1 : 1'b0);

assign icmp_ln236_fu_431_p2 = (($signed(roi_h_fu_404_p3) < $signed(8'd1)) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_192_p2 = (($signed(n_reg_491) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign input_rgb_address0 = grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_address0;

assign input_rgb_ce0 = grp_card_recognizer_hw_Pipeline_GRAYSCALE_LOOP_fu_150_input_rgb_ce0;

assign roi_h_1_fu_437_p3 = ((icmp_ln236_fu_431_p2[0:0] == 1'b1) ? 7'd1 : trunc_ln234_1_fu_409_p1);

assign roi_h_fu_404_p3 = ((tmp_2_reg_543[0:0] == 1'b1) ? sub_ln234_1_reg_574 : tmp_1_cast_reg_569);

assign roi_w_1_fu_419_p3 = ((icmp_ln235_fu_413_p2[0:0] == 1'b1) ? 9'd1 : trunc_ln233_fu_400_p1);

assign roi_w_fu_393_p3 = ((tmp_reg_554[0:0] == 1'b1) ? sub_ln233_1_fu_380_p2 : zext_ln233_2_fu_389_p1);

assign select_ln234_fu_357_p3 = ((tmp_2_reg_543[0:0] == 1'b1) ? tmp_cast_fu_338_p4 : tmp_1_cast_fu_348_p4);

assign sext_ln231_fu_276_p1 = sub_ln230_fu_270_p2;

assign sext_ln233_1_fu_373_p1 = $signed(trunc_ln233_1_reg_559);

assign sext_ln233_2_fu_386_p1 = $signed(trunc_ln233_2_reg_564);

assign sext_ln233_fu_239_p1 = $signed(sub_ln231_fu_233_p2);

assign sub_ln230_fu_270_p2 = (9'd1 - zext_ln230_1_fu_264_p1);

assign sub_ln231_fu_233_p2 = (9'd1 - zext_ln231_fu_225_p1);

assign sub_ln233_1_fu_380_p2 = (10'd0 - zext_ln233_1_fu_376_p1);

assign sub_ln233_fu_303_p2 = (9'd0 - add_ln233_1_fu_289_p2);

assign sub_ln234_1_fu_364_p2 = (8'd0 - select_ln234_fu_357_p3);

assign sub_ln234_fu_332_p2 = (20'd0 - trunc_ln234_fu_329_p1);

assign tmp_1_cast_fu_348_p4 = {{grp_fu_464_p2[19:12]}};

assign tmp_cast_fu_338_p4 = {{sub_ln234_fu_332_p2[19:12]}};

assign trunc_ln233_fu_400_p1 = roi_w_fu_393_p3[8:0];

assign trunc_ln234_1_fu_409_p1 = roi_h_fu_404_p3[6:0];

assign trunc_ln234_fu_329_p1 = grp_fu_464_p2[19:0];

assign trunc_ln246_fu_261_p1 = width_read_reg_478[14:0];

assign trunc_ln33_fu_197_p1 = n_reg_491[30:0];

assign x1_fu_449_p2 = (zext_ln233_3_fu_427_p1 + zext_ln230_fu_370_p1);

assign y1_fu_455_p2 = (zext_ln234_fu_445_p1 + zext_ln231_reg_533);

assign zext_ln230_1_fu_264_p1 = card_box_min_x_V_reg_506;

assign zext_ln230_2_fu_267_p1 = card_box_max_x_V_reg_518;

assign zext_ln230_fu_370_p1 = card_box_min_x_V_reg_506;

assign zext_ln231_1_fu_229_p1 = grp_find_largest_component_ccl_fu_168_ap_return_3;

assign zext_ln231_fu_225_p1 = grp_find_largest_component_ccl_fu_168_ap_return_1;

assign zext_ln233_1_fu_376_p1 = $unsigned(sext_ln233_1_fu_373_p1);

assign zext_ln233_2_fu_389_p1 = $unsigned(sext_ln233_2_fu_386_p1);

assign zext_ln233_3_fu_427_p1 = roi_w_1_fu_419_p3;

assign zext_ln233_fu_280_p1 = card_box_max_x_V_reg_518;

assign zext_ln234_fu_445_p1 = roi_h_1_fu_437_p3;

always @ (posedge ap_clk) begin
    zext_ln231_reg_533[8] <= 1'b0;
end

endmodule //card_recognizer_hw
