-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity card_recognizer_hw_find_largest_component_ccl_Pipeline_INIT_COMPONENTS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    parent_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    parent_V_ce0 : OUT STD_LOGIC;
    parent_V_we0 : OUT STD_LOGIC;
    parent_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    min_x_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    min_x_V_ce0 : OUT STD_LOGIC;
    min_x_V_we0 : OUT STD_LOGIC;
    min_x_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    min_y_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    min_y_V_ce0 : OUT STD_LOGIC;
    min_y_V_we0 : OUT STD_LOGIC;
    min_y_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    max_x_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    max_x_V_ce0 : OUT STD_LOGIC;
    max_x_V_we0 : OUT STD_LOGIC;
    max_x_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    max_y_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    max_y_V_ce0 : OUT STD_LOGIC;
    max_y_V_we0 : OUT STD_LOGIC;
    max_y_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    count_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    count_ce0 : OUT STD_LOGIC;
    count_we0 : OUT STD_LOGIC;
    count_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of card_recognizer_hw_find_largest_component_ccl_Pipeline_INIT_COMPONENTS is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_9F : STD_LOGIC_VECTOR (7 downto 0) := "10011111";
    constant ap_const_lv8_77 : STD_LOGIC_VECTOR (7 downto 0) := "01110111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln105_fu_137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln105_fu_149_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_1_fu_42 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_2_fu_143_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component card_recognizer_hw_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component card_recognizer_hw_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_42_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                if ((icmp_ln105_fu_137_p2 = ap_const_lv1_0)) then 
                    i_1_fu_42 <= i_2_fu_143_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_42 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln105_fu_137_p2, ap_start_int)
    begin
        if (((icmp_ln105_fu_137_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_state1, i_1_fu_42, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i <= i_1_fu_42;
        end if; 
    end process;

    count_address0 <= zext_ln105_fu_149_p1(8 - 1 downto 0);

    count_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            count_ce0 <= ap_const_logic_1;
        else 
            count_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    count_d0 <= ap_const_lv32_0;

    count_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln105_fu_137_p2, ap_start_int)
    begin
        if (((icmp_ln105_fu_137_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            count_we0 <= ap_const_logic_1;
        else 
            count_we0 <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_143_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv9_1));
    icmp_ln105_fu_137_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv9_100) else "0";
    max_x_V_address0 <= zext_ln105_fu_149_p1(8 - 1 downto 0);

    max_x_V_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            max_x_V_ce0 <= ap_const_logic_1;
        else 
            max_x_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    max_x_V_d0 <= ap_const_lv8_0;

    max_x_V_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln105_fu_137_p2, ap_start_int)
    begin
        if (((icmp_ln105_fu_137_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            max_x_V_we0 <= ap_const_logic_1;
        else 
            max_x_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    max_y_V_address0 <= zext_ln105_fu_149_p1(8 - 1 downto 0);

    max_y_V_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            max_y_V_ce0 <= ap_const_logic_1;
        else 
            max_y_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    max_y_V_d0 <= ap_const_lv8_0;

    max_y_V_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln105_fu_137_p2, ap_start_int)
    begin
        if (((icmp_ln105_fu_137_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            max_y_V_we0 <= ap_const_logic_1;
        else 
            max_y_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    min_x_V_address0 <= zext_ln105_fu_149_p1(8 - 1 downto 0);

    min_x_V_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            min_x_V_ce0 <= ap_const_logic_1;
        else 
            min_x_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    min_x_V_d0 <= ap_const_lv8_9F;

    min_x_V_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln105_fu_137_p2, ap_start_int)
    begin
        if (((icmp_ln105_fu_137_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            min_x_V_we0 <= ap_const_logic_1;
        else 
            min_x_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    min_y_V_address0 <= zext_ln105_fu_149_p1(8 - 1 downto 0);

    min_y_V_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            min_y_V_ce0 <= ap_const_logic_1;
        else 
            min_y_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    min_y_V_d0 <= ap_const_lv8_77;

    min_y_V_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln105_fu_137_p2, ap_start_int)
    begin
        if (((icmp_ln105_fu_137_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            min_y_V_we0 <= ap_const_logic_1;
        else 
            min_y_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    parent_V_address0 <= zext_ln105_fu_149_p1(8 - 1 downto 0);

    parent_V_ce0_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            parent_V_ce0 <= ap_const_logic_1;
        else 
            parent_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    parent_V_d0 <= ap_sig_allocacmp_i(8 - 1 downto 0);

    parent_V_we0_assign_proc : process(ap_CS_fsm_state1, icmp_ln105_fu_137_p2, ap_start_int)
    begin
        if (((icmp_ln105_fu_137_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            parent_V_we0 <= ap_const_logic_1;
        else 
            parent_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln105_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i),64));
end behav;
