-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity card_recognizer_hw_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    card_box_min_y_V : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln246_1 : IN STD_LOGIC_VECTOR (8 downto 0);
    trunc_ln9 : IN STD_LOGIC_VECTOR (14 downto 0);
    card_box_min_x_V : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln246 : IN STD_LOGIC_VECTOR (9 downto 0);
    roi_count_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    roi_count_2_out_ap_vld : OUT STD_LOGIC;
    binary_V_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    binary_V_ce0 : OUT STD_LOGIC;
    binary_V_q0 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of card_recognizer_hw_card_recognizer_hw_Pipeline_ROI_Y_LOOP_ROI_X_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv15_4B00 : STD_LOGIC_VECTOR (14 downto 0) := "100101100000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln246_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln246_reg_419 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln246_reg_419_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln246_reg_419_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln246_fu_215_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln246_reg_423 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln246_reg_423_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln252_1_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln252_1_reg_433 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln252_1_reg_433_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln252_1_reg_433_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln252_1_reg_433_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln541_fu_339_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal roi_count_1_fu_70 : STD_LOGIC_VECTOR (31 downto 0);
    signal roi_count_fu_360_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal x_fu_74 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln249_fu_315_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_x_load : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fu_78 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln246_1_fu_237_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_y_2 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_fu_82 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln246_fu_200_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln246_3_fu_166_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ult_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln246_2_fu_162_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal notrhs_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev20_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln246_1_fu_223_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln246_5_fu_233_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ult21_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln246_4_fu_229_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal notrhs_mid1_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev22_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln252_3_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln252_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln252_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln251_fu_281_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln252_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln252_1_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln252_2_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln246_2_fu_273_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln541_fu_339_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_376_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln255_fu_346_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal roi_count_2_fu_352_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_376_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_376_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_376_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_376_p20 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component card_recognizer_hw_mac_muladd_7ns_15s_8ns_15_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component card_recognizer_hw_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_7ns_15s_8ns_15_4_1_U69 : component card_recognizer_hw_mac_muladd_7ns_15s_8ns_15_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 7,
        din1_WIDTH => 15,
        din2_WIDTH => 8,
        dout_WIDTH => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_376_p0,
        din1 => trunc_ln9,
        din2 => grp_fu_376_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_376_p3);

    flow_control_loop_pipe_sequential_init_U : component card_recognizer_hw_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln246_fu_194_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_82 <= add_ln246_fu_200_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_82 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    roi_count_1_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    roi_count_1_fu_70 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    roi_count_1_fu_70 <= roi_count_fu_360_p3;
                end if;
            end if; 
        end if;
    end process;

    x_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln246_fu_194_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_74 <= add_ln249_fu_315_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_74 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    y_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln246_fu_194_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    y_fu_78 <= select_ln246_1_fu_237_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_78 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln246_fu_194_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln252_1_reg_433 <= and_ln252_1_fu_309_p2;
                select_ln246_reg_423 <= select_ln246_fu_215_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln252_1_reg_433_pp0_iter1_reg <= and_ln252_1_reg_433;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln246_reg_419 <= icmp_ln246_fu_194_p2;
                icmp_ln246_reg_419_pp0_iter1_reg <= icmp_ln246_reg_419;
                select_ln246_reg_423_pp0_iter1_reg <= select_ln246_reg_423;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln252_1_reg_433_pp0_iter2_reg <= and_ln252_1_reg_433_pp0_iter1_reg;
                and_ln252_1_reg_433_pp0_iter3_reg <= and_ln252_1_reg_433_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln246_reg_419_pp0_iter2_reg <= icmp_ln246_reg_419_pp0_iter1_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln246_1_fu_223_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_y_2) + unsigned(ap_const_lv7_1));
    add_ln246_fu_200_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv15_1));
    add_ln249_fu_315_p2 <= std_logic_vector(unsigned(select_ln246_fu_215_p3) + unsigned(ap_const_lv8_1));
    add_ln255_fu_346_p2 <= std_logic_vector(unsigned(roi_count_1_fu_70) + unsigned(ap_const_lv32_1));
    and_ln252_1_fu_309_p2 <= (select_ln246_2_fu_273_p3 and and_ln252_2_fu_303_p2);
    and_ln252_2_fu_303_p2 <= (xor_ln252_fu_291_p2 and icmp_ln252_1_fu_297_p2);
    and_ln252_3_fu_267_p2 <= (rev22_fu_255_p2 and notrhs_mid1_fu_261_p2);
    and_ln252_fu_188_p2 <= (rev20_fu_176_p2 and notrhs_fu_182_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln246_fu_194_p2)
    begin
        if (((icmp_ln246_fu_194_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_82)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_82;
        end if; 
    end process;


    ap_sig_allocacmp_x_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, x_fu_74)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_x_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_x_load <= x_fu_74;
        end if; 
    end process;


    ap_sig_allocacmp_y_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, y_fu_78)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_y_2 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_y_2 <= y_fu_78;
        end if; 
    end process;

    binary_V_address0 <= zext_ln541_fu_339_p1(15 - 1 downto 0);

    binary_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            binary_V_ce0 <= ap_const_logic_1;
        else 
            binary_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_376_p0 <= grp_fu_376_p00(7 - 1 downto 0);
    grp_fu_376_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln246_1_fu_237_p3),15));
    grp_fu_376_p2 <= grp_fu_376_p20(8 - 1 downto 0);
    grp_fu_376_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln246_reg_423_pp0_iter1_reg),15));
    icmp_ln246_fu_194_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv15_4B00) else "0";
    icmp_ln249_fu_209_p2 <= "1" when (ap_sig_allocacmp_x_load = ap_const_lv8_A0) else "0";
    icmp_ln252_1_fu_297_p2 <= "1" when (unsigned(zext_ln251_fu_281_p1) < unsigned(zext_ln246)) else "0";
    icmp_ln252_fu_285_p2 <= "1" when (unsigned(select_ln246_fu_215_p3) < unsigned(card_box_min_x_V)) else "0";
    notrhs_fu_182_p2 <= "1" when (unsigned(zext_ln246_2_fu_162_p1) < unsigned(zext_ln246_1)) else "0";
    notrhs_mid1_fu_261_p2 <= "1" when (unsigned(zext_ln246_4_fu_229_p1) < unsigned(zext_ln246_1)) else "0";
    rev20_fu_176_p2 <= (ult_fu_170_p2 xor ap_const_lv1_1);
    rev22_fu_255_p2 <= (ult21_fu_249_p2 xor ap_const_lv1_1);
    roi_count_2_fu_352_p3 <= 
        add_ln255_fu_346_p2 when (binary_V_q0(0) = '1') else 
        roi_count_1_fu_70;
    roi_count_2_out <= roi_count_1_fu_70;

    roi_count_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln246_reg_419_pp0_iter2_reg)
    begin
        if (((icmp_ln246_reg_419_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            roi_count_2_out_ap_vld <= ap_const_logic_1;
        else 
            roi_count_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    roi_count_fu_360_p3 <= 
        roi_count_2_fu_352_p3 when (and_ln252_1_reg_433_pp0_iter3_reg(0) = '1') else 
        roi_count_1_fu_70;
    select_ln246_1_fu_237_p3 <= 
        add_ln246_1_fu_223_p2 when (icmp_ln249_fu_209_p2(0) = '1') else 
        ap_sig_allocacmp_y_2;
    select_ln246_2_fu_273_p3 <= 
        and_ln252_3_fu_267_p2 when (icmp_ln249_fu_209_p2(0) = '1') else 
        and_ln252_fu_188_p2;
    select_ln246_fu_215_p3 <= 
        ap_const_lv8_0 when (icmp_ln249_fu_209_p2(0) = '1') else 
        ap_sig_allocacmp_x_load;
    ult21_fu_249_p2 <= "1" when (unsigned(zext_ln246_5_fu_233_p1) < unsigned(card_box_min_y_V)) else "0";
    ult_fu_170_p2 <= "1" when (unsigned(zext_ln246_3_fu_166_p1) < unsigned(card_box_min_y_V)) else "0";
    xor_ln252_fu_291_p2 <= (icmp_ln252_fu_285_p2 xor ap_const_lv1_1);
    zext_ln246_2_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_y_2),9));
    zext_ln246_3_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_y_2),8));
    zext_ln246_4_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln246_1_fu_223_p2),9));
    zext_ln246_5_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln246_1_fu_223_p2),8));
    zext_ln251_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln246_fu_215_p3),10));
    zext_ln541_fu_339_p0 <= grp_fu_376_p3;
    zext_ln541_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln541_fu_339_p0),64));
end behav;
